### ISSUE TITLE
VolVoices from UTK does not meet minimum requirements for metadata sharing in DPLA

### ISSUE THREAD

**Issue by markpbaggett** [DigitalLibraryofTennessee/DLTN_XSLT#134]
## Why are You Reporting an Issue

- [ ] Add New Set(s)
- [ ] Reingest Existing Set
- [x] Report Problem with an Existing Set or XSL transform
- [ ] Discuss Issue or Ask Question
- [ ] Other

## New Set(s) / Reharvest Existing Set

The utk_volvoices set in Repox does not meet the minimum requirements for sharing to DPLA. We either need to modify our transform to handle this, remove this set from sharing (yikes!), or fix the metadata to meet the minimum requirements for sharing.

Is there an update about where we are with this metadata migration? I think fixing this for our March ingest should be our primary priority.

**Comment by mlhale7** [comment]
@markpbaggett - I'd agree that this should be a high priority (we definitely don't want to remove the set). I finished out the work we still had to do on remediating names, but I haven't worked on it since. I'll start working away at it again and plan to finish by mid March.

**Comment by markpbaggett** [comment]
So obviously I didn't test that the metadata met minimum qualifications last year when the new objects were added.  I'm going to add a test in the template to make this minimally shareable.

**Comment by markpbaggett** [comment]
@mlhale7, don't worry about that.  I'm mostly worried about this not meeting minimum standards.  Don't change your plans to complete work that you weren't planning to do for this time.  We can get over this hurdle by just fixing the transform for now.
