### ISSUE TITLE
utk_colloquy in Repox has bad accessConditions

### ISSUE THREAD

**Issue by markpbaggett** [DigitalLibraryofTennessee/DLTN_XSLT#139]
## Why are You Reporting an Issue

- [ ] Add New Set(s)
- [ ] Reingest Existing Set
- [x] Report Problem with an Existing Set or XSL transform
- [ ] Discuss Issue or Ask Question
- [ ] Other

## Problem with Set or Transform

The colloquy records in Repox all have bad access conditions.  These records need to be reharvested in DPLA so that they have valid rights statements in DPLA.

**Comment by mlhale7** [comment]
@markpbaggett - It looks like this collection has a lot of issues with leading and trailing whitespace throughout, but otherwise is fine.

**Comment by markpbaggett** [comment]
@mlhale7, the lack of normalized spacing didn't matter, but the bad xpath for accessConditions did.  I just reharvested and everything passes tests defined in [check_and_harvest](https://github.com/DigitalLibraryofTennessee/check_and_harvest). Closing since this set is already in DPLA.
