### ISSUE TITLE
New Set: Chattanooga Latinx Oral Histories

### ISSUE THREAD

**Issue by carolynfrunyon** [DigitalLibraryofTennessee/DLTN_XSLT#145]
## Why are You Reporting an Issue

- [x] Add New Set(s)
- [ ] Reingest Existing Set
- [ ] Report Problem with an Existing Set or XSL transform
- [ ] Discuss Issue or Ask Question
- [ ] Other

## New Set(s) / Reharvest Existing Set

Only required if you're requesting sets to be added or reharvested.

* p16877coll31

Thank you so much for all of your help! It is much appreciated!

**Comment by mlhale7** [comment]
@carolynfrunyon - I've added this set. Thanks for letting us know.

**Comment by carolynfrunyon** [comment]
That was fast! Thanks @mlhale7!

**Comment by markpbaggett** [comment]
@mlhale7, just a reminder.  If this set isn't added to description [here](https://github.com/DigitalLibraryofTennessee/DLTN_XSLT/issues/140) it likely will not end up in DPLA this ingest.

**Comment by mlhale7** [comment]
@markpbaggett - Thanks, I had created a separate list for my annual statistics that documents each set and the number of records by ingest. I'll work to add these here in the future.
