### ISSUE TITLE
UTKmodstomods.xsl can't handle multiple role/roleTerms

### ISSUE THREAD

**Issue by markpbaggett** [DigitalLibraryofTennessee/DLTN_XSLT#159]
## Why are You Reporting an Issue

- [ ] Add New Set(s)
- [ ] Reingest Existing Set
- [x] Report Problem with an Existing Set or XSL transform
- [ ] Discuss Issue or Ask Question
- [ ] Other

## Problem with Set or Transform

Currently, we have a problem transforming metadata where a name has 2 role/roleTerms with utkmodstomods.xsl.  For example, this data:

```
  <name>
    <namePart>Mooers, George A.</namePart>
    <role>
      <roleTerm authority="marcrelator" valueURI="http://id.loc.gov/vocabulary/relators/edt">Editor</roleTerm>
      <roleTerm authority="marcrelator" valueURI="http://id.loc.gov/vocabulary/relators/art">Artist</roleTerm>
    </role>
  </name>
```

It cannot be processed by this: 

```
<xsl:variable name="vRole" select="normalize-space(role[1]/roleTerm)"/>
```

Since we're just transforming to either a creator or contributor, let's just look at the first roleTerm.

**Comment by markpbaggett** [comment]
@mlhale7 and @CanOfBees,

The above is valid, but after reading [guidelines for use](https://www.loc.gov/standards/mods/userguide/name.html#role), this sounds wrong:

> role is a container element for the role recorded in one or more roleTerm subelements.
> If there are different roles, repeat /role/roleTerm as needed. 

To me, it seems that the idea here should be if you have multiple terms that describe the same role, it's repeatable in the same role node, but if you have different roles, you repeat role/roleTerm.

Regardless, we have a problem because we could have multiple roleTerms in one role, but I still think the data here is wrong.

Thoughts?

**Comment by CanOfBees** [comment]
@markpbaggett I agree - it does look like a data problem (see [the Book example in the Guidelines](https://www.loc.gov/standards/mods/userguide/examples.html#digitized_book)).

I'll work up a PR and submit.

**Comment by markpbaggett** [comment]
@CanOfBees, a p.r. for what: the data or the problem with the transform?  I have a fix for the transform, but am waiting until the p.r. for DLTN_XSLT-160 is reviewed, approved, and merged.  That needs to be the priority -- getting baseline unit testing working.

**Comment by CanOfBees** [comment]
@markpbaggett  apologies; I'm not moving as fast as you are on this. I just saw the -160 PR. I'll make that the priority.
