### ISSUE TITLE
concat() acts weird when you pass it following axes

### ISSUE THREAD

**Issue by markpbaggett** [DigitalLibraryofTennessee/DLTN_XSLT#163]
## Why are You Reporting an Issue

- [ ] Add New Set(s)
- [ ] Reingest Existing Set
- [x] Report Problem with an Existing Set or XSL transform
- [ ] Discuss Issue or Ask Question
- [ ] Other

## Problem with Set or Transform

These are the affected sets:

1. utk_arrscrap
2. utk_derris
3. utk_voice
4. utk_univmonthly
5. utk_humbug

So, I can't tell how big of a problem this is, but I can say saxon8.7 on my local machine and in travis has this.  9 whatever in Oxygen also shows this behaviour.

If you do something like this, all 3 of these things freak out.  8.7 blows up, but 9 whatever takes the value of multiple things:

```
<xsl:value-of select="concat(following::identifier[starts-with(.,'https://')]],'/datastream/TN/view')"/>
```

Oddly, there are no problems with this approach if you don't pass the output to concat() first.

This seems to work fine and I recommend this approach:

```
            <xsl:if test="not(url[@access='preview'])">
                <xsl:variable name="concat_val" select="following::identifier[starts-with(.,'https://')]"/>
                <xsl:element name="url">
                    <xsl:attribute name="access">
                        <xsl:value-of select="'preview'"/>
                    </xsl:attribute>
                    <xsl:value-of select="concat($concat_val[1],'/datastream/TN/view')"/>
                </xsl:element>
            </xsl:if>
```

Thoughts?  @CanOfBees or @mlhale7

**Comment by CanOfBees** [comment]
@markpbaggett Okay, hopefully I didn't mess up *which* transform I'm supposed to be looking at for this. There's some context here: when we run tests (e.g. `${SOME_UTK_SET} utkmodstomods.xsl`), we're using the full OAI-PMH response, but when this runs in REPOX it's running against a single `record` node(); I think that might be contributing to this weird behavior. 

But maybe not. Let's talk about this some more.

Alternately, changing `concat(following::identifier[...],'...')` to `concat(following-sibling::identifier[...],'...')` should work for both contexts (e.g. running in REPOX and running in automated tests where we have a slightly different XML structure).

**Comment by markpbaggett** [comment]
@CanOfBees, I think you are right, but I don't think that's okay.  Unless we want to split responses into individual XML files before unit testing, this is a problem, but your solution makes this works regardless.

Do we really need to discuss?  If so, let's do so here.  I like your solution and have opened p.r. 166.

**Comment by CanOfBees** [comment]
@markpbaggett I don't think there's a need to discuss - I'll take a longer look at that PR now. Thanks!
