### ISSUE TITLE
dloai transform causing validity problems related to order in location node

### ISSUE THREAD

**Issue by markpbaggett** [DigitalLibraryofTennessee/DLTN_XSLT#165]
## Why are You Reporting an Issue

- [ ] Add New Set(s)
- [ ] Reingest Existing Set
- [x] Report Problem with an Existing Set or XSL transform
- [ ] Discuss Issue or Ask Question
- [ ] Other

## Problem with Set or Transform

These sets are affected:

1. utk_charlie
2. utk_scopes
3. utk_volvoices
4. utk_adams

The incoming data from dloai isn't valid because of something happening in that transform.  It's fine our of Islandora directly.  Where the heck is that transform? :angry: 

@CanOfBees  @mlhale7

**Comment by pc37utn** [comment]
I have the scripts and transforms in a repo, it is private and I'll add you to it.

**Comment by mlhale7** [comment]
I believe we addressed this issue with https://github.com/utkdigitalinitiatives/oai-mods-add-urls/pull/2. Please reopen if not.
