### ISSUE TITLE
Country Music Hall of Fame and Museum: adding Hatch dataset

### ISSUE THREAD

**Issue by lboulie2** [DigitalLibraryofTennessee/DLTN_XSLT#168]
- [x] Add New Set(s)

http://digi.countrymusichalloffame.org/cdm/search/collection/hatch3

http://cmfdigitization.cmf.int:2011/oai/oai.php

We are currently moving from a local install to a hosted version of CONTENTdm. Please let me know if you need further information.

Thanks,
Lee Boulie

**Comment by lboulie2** [comment]
I would guess it’s because of the move—we aren’t able to do any work in the project client or make edits to existing records currently. That said, it could be unrelated. I’ll check with our tech people and see if they have any ideas.

Thanks!
Lee

**Comment by markpbaggett** [comment]
@lboulie2 my assumption is this is your OAI link:

http://digi.countrymusichalloffame.org/oai/oai.php?verb=ListSets

And we can just harvest this for hatch:

http://digi.countrymusichalloffame.org/oai/oai.php?verb=ListRecords&metadataPrefix=oai_qdc&set=hatch3

Am I missing something?

**Comment by mlhale7** [comment]
@markpbaggett - thanks. Our Wiki had a slightly different OAI endpoint listed (now updated) and the one Lee provided wasn't working. We can definitely use the link that you've shared so we should be all set @lboulie2. I assume this endpoint will continue to be active for a bit.

**Comment by lboulie2** [comment]
Thanks, Mark. That sounds good. Will that harvest all 19,967 Hatch records?

**Comment by markpbaggett** [comment]
@mlhale7, I wouldn't go off the wiki.  We really stopped using it in Spring 2017 when members of the DLTN committee complained about not being able to contribute data there.  The plan was to use GitHub pages, but nothing ever happened their.  Let's go off the [technical docs](https://dltn-technical-docs.readthedocs.io/en/latest/providers/CountryMusicHallofFamer0.html) page.

**Comment by lboulie2** [comment]
We’ll continue to add to that endpoint for about 18 months—we are scanning the entirety of our hatch archives.

For future reference, so I make sure I send the correct OAI endpoint, where should I find that? I just sent the one listed in CONTENTdm admin.

Thanks to both of you for your work on this—much appreciated.

Lee

**Comment by markpbaggett** [comment]
@lboulie2,

Unless something radical changes, I don't think you need to send the OAI endpoint.  We'll assume you still have the same instance of ContentDM.  If the URI for your ContentDM instance was to change, then we'd need to know.  As long as you're using ContentDM, we can guess the OAI endpoint as it tends to be consistent based on the version of ContentDM that is running.  

We keep a page in our technical documentation that tracks this kind of thing.  You can see the one for CMHF here:

https://dltn-technical-docs.readthedocs.io/en/latest/providers/CountryMusicHallofFamer0.html

I'll run check and harvest versus hatch3 now and make sure there are no issues real quick and update this ticket.

**Comment by mlhale7** [comment]
It looks like you actually have 21,010 records pulling the OAI. I'll let Mark comment if we have any issues.

**Comment by lboulie2** [comment]
You rock. Big thanks.

**Comment by lboulie2** [comment]
Great. (I was counting each compound object as 1.) Many thanks.

**Comment by markpbaggett** [comment]
So there are 17292 good records (2675 records have a problem). It looks like the majority of the ones that are coming back as bad are due to missing rights statements.  

We have a few options:

1. We could blanket your rights statement if they are all exactly the same here.
2. You could do the same on your end.
3. We can take just the 17292 good ones for now.

@lboulie2, what's your preference here?  Is there anything we could help with?

**Comment by lboulie2** [comment]
Can you blanket the rights statements? I feel like that’s a lot to ask, but we are in a holding pattern with our metadata, and have been asked to not make any changes as we move to the hosted solution.

If it’s easiest to just take the good ones, then that’s ok too. We can fix the others later on our end.

Thank you so much. I’m excited to see these added!

**Comment by markpbaggett** [comment]
Absolutely.  As long as there is no logic, we can do that easily.

**Comment by lboulie2** [comment]
Thank you!

**Comment by lboulie2** [comment]
Hi Mark,

Does this mean our Hatch records were harvested and added to DLTN? Just making sure I know what to tell people.

Many thanks,
Lee

Lee Boulie
Executive Director of Digital & Library Collections

Country Music Hall of Fame® and Museum
222 Fifth Avenue South | Nashville, TN 37203
615-291-8423 desk

**Comment by mlhale7** [comment]
@lboulie2 - this means that the hatch set has been successfully added to Repox, which aggregates all of our data for sharing with DPLA. The set will actually be shared with DPLA (and subsequently DLTN) the week of June 17th during our ingest. Let us know if you have any other questions and thanks for this great set.

**Comment by lboulie2** [comment]
Hooray! Thank you ☺

Lee Boulie
Executive Director of Digital & Library Collections

Country Music Hall of Fame® and Museum
222 Fifth Avenue South | Nashville, TN 37203
615-291-8423 desk

**Comment by lboulie2** [comment]
Hi,

Just wanted to check on this. I’m not seeing all the items uploaded to DLTN. Am I just looking in the wrong place?

Thanks!
Lee

Lee Boulie
Executive Director of Digital & Library Collections

Country Music Hall of Fame® and Museum
222 Fifth Avenue South | Nashville, TN 37203
615-291-8423 desk

**Comment by lboulie2** [comment]
I just answered my own question—sorry. And thanks for getting those up!!!

From: Lee Boulie
Sent: Monday, June 24, 2019 12:09 PM
To: 'DigitalLibraryofTennessee/DLTN_XSLT' <reply@reply.github.com>; DigitalLibraryofTennessee/DLTN_XSLT <DLTN_XSLT@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [DigitalLibraryofTennessee/DLTN_XSLT] Country Music Hall of Fame and Museum: adding Hatch dataset (#168)

Hi,

Just wanted to check on this. I’m not seeing all the items uploaded to DLTN. Am I just looking in the wrong place?

Thanks!
Lee

Lee Boulie
Executive Director of Digital & Library Collections

Country Music Hall of Fame® and Museum
222 Fifth Avenue South | Nashville, TN 37203
615-291-8423 desk

**Comment by mlhale7** [comment]
@lboulie2 - I believe our ingest just went through fully yesterday. On DPLA, all of CMHF's materials are [here](https://dp.la/search?q=&partner=%22Digital%20Library%20of%20Tennessee%22&page=1&provider=%22Country%20Music%20Hall%20of%20Fame%20and%20Museum%22). On DLTN, you can find them [here](https://tn.dp.la/search?q=&provider=%22Country%20Music%20Hall%20of%20Fame%20and%20Museum%22&page=1). If you just want to share the Hatch materials in particular, you'd need to find a common value in your metadata. It doesn't look like you've included "Hatch Show Print (Firm)" in all of your records. It also doesn't look like the note values are present in DPLA, so don't use those. If you believe you are still missing records after looking at these links definitely let us know. We have yet to receive the error reports from the ingest to analyze any potential problems. Our numbers did go up to over 100,000 records this ingest, so upon initial review it does look like the new hatch records should've went through.
