### ISSUE TITLE
TSLA June 2019 Ingest

### ISSUE THREAD

**Issue by jrandlestsla** [DigitalLibraryofTennessee/DLTN_XSLT#169]
## Why are You Reporting an Issue

- [x] Add New Set(s)
- [x] Reingest Existing Set
- [ ] Report Problem with an Existing Set or XSL transform
- [ ] Discuss Issue or Ask Question
- [ ] Other

## New Set(s) / Reharvest Existing Set

Only required if you're requesting sets to be added or reharvested.

* p15138coll47
* p15138coll45
* p15138coll27
* reconaa
* Fisk
* p15138coll39
* p15138coll29
* p15138coll40

## Discuss Issue or Ask Question
A couple of these were included in the last ingest request, but they don't appear in DPLA.  Did all of those harvests go through? Specifically, I couldn't find Frank Hodge papers, Cartmell Diaries, or Fisk Scrapbook, but did find Grassmere. All of these were in the last harvest.

**Comment by mlhale7** [comment]
@jrandlestsla - Apologies for the delayed response on this. Looking through the collections you noticed as missing, I have identified some items in DPLA from the collections you mentioned. Are there particular records you cannot find that I should look into further?

Fisk (sampling of items available in DPLA): 
1. https://dp.la/item/f66ba2db8273d99c28036e1afa7136b4
2. https://dp.la/item/87e1bb88cbda9ea178498a5ac1e3ec0d
3. https://dp.la/item/b17f4a9674da87f68d29632e7d5536c5

Cartmell Diaries (sampling of items available in DPLA):
1. https://dp.la/item/c7b85a5e2f743d4b374372a09600c4d1
2. https://dp.la/item/47f62f4307a5defc65d097bc519cc59
3. https://dp.la/item/b1d0626f8a4536eeb2cf6ada28cb1df0

The Frank Hodge papers are indeed missing from DPLA. Unfortunately the wrong transform was applied to this set and it made the resulting data be rejected. Sorry for this error. It will be set for the next ingest.

I'll reply to this ticket again when I have a chance to QA and add the new and updated sets (reconaa, etc.)

**Comment by markpbaggett** [comment]
@mlhale7 and @jrandlestsla, 

I'm not sure what specifically is missing, but I wanted to point out some things in case it would help:

1. Fisk:  This was last ingested on 11/09/2018 08:57:37
2. reconaa: This was last ingested on '07/10/2015 19:30:39'.  I assume this may be why some of this is missing.
3. p15138coll47 is not there. We'll add this one.
4. p15138coll45 was last ingested on 04/17/2019 17:07:07.  I think this is the one where we actually added it as oai_dc but associated the qdc transform so it was blocked from getting into DPLA last ingest.
5. p15138coll40 was last ingested on '12/04/2017 16:53:15'. I'm assuming there is probably a lot of things we are missing.
6. p15138coll27 was last ingested on '12/04/2017 17:27:16'.  I'm assuming there is probably a lot of things we are missing.
7. p15138coll39 was last ingested on '11/09/2018 09:17:52'. If there has been any new additions, we wouldn't have them.
8. p15138coll29 was last ingested on '11/27/2018 15:49:37'. If there has been any new additions, we wouldn't have them.  

Let me take a look of each of this sets and see how things have changed.  We may need to readd some of the very old sets with [check_and_harvest](https://github.com/digitallibraryoftennessee/check_and_harvest) to avoid pulling in bad records.

Depending on the complexity here, we may want to split this into separate tickets to ensure we don't miss anything.

**Comment by jrandlestsla** [comment]
It's weird, when I perform those searches now, the items show up. But for some reason, they didn't before. A lot of those I listed didn't have problems, I just knew they had been updated in the past year or so. Thanks for checking into things.

**Comment by markpbaggett** [comment]
Fisk has been reharvested.

**Comment by markpbaggett** [comment]
This should be done once [DLTN_XSLT-174](https://github.com/DigitalLibraryofTennessee/DLTN_XSLT/issues/174) has been reviewed and merged and the template has been updated on server.

**Comment by markpbaggett** [comment]
@jrandlestsla, these have all been added and are ready for the June harvest.
