### ISSUE TITLE
Problem with Mapping of 2 MTSU Sets

### ISSUE THREAD

**Issue by markpbaggett** [DigitalLibraryofTennessee/DLTN_XSLT#18]
## Why are You Reporting an Issue

- [ ] Add New Set(s)
- [ ] Reingest Existing Set
- [x] Report Problem with an Existing Set or XSL transform

## New Set(s) / Reingest Existing Set

* cannon
* southernplaces

## Problem with Set or Transform

This is an email sent by @kmiddlet regarding problems with 2 sets.  Adding this for him here. 

**Problem 1**

> In our "Cannon County Collection," for some reason I mapped "collection" to "title."
> So all records in this collection are displaying in DPLA with "Photographs of W.L. Clement, U.S. Soil Conservation Service" as title rather than the actual title:
> https://dp.la/search?utf8=%E2%9C%93&q=%22Photographs+of+W.L.+Clement%2C+U.S.+Soil+Conservation+Service%22
> 

**Problem 2**

> Southern Places Collection - Same display issue because "Collection" is not mapped at all. I'm going to go ahead and change it to map "collection" to "dc:relation.isPartOf" in these two collections if that is ok.

The other collections are fine because they either do not include a "collection" field or this field was mapped correctly (e.g., MTSU Memory).

Is there enough time to reharvest these collections before dpla does their thing?
If not, it sounds like they are getting things together and that it should not be too long after the next batch.

Sorry about this oversight.

**Comment by markpbaggett** [comment]
@kmiddlet, 

**for Problem 1**:

 are you able to remap title to collection and collection to title easily using ContentDM.  I'm adding @carolynfrunyon here in case she has advice doing this in ContentDM.

**For Problem 2:**

Just a warning:  we're still pulling out your stuff as simple dc, so we're only going to be able to access dc:relation.  We just need to make sure that your mapping is putting this in dc:relation, but I know @carolynfrunyon is doing something similar so maybe this automatically ends up there when you put this in dc:relation.isPartOf

**Finally:**

As far as I know, they still haven't done anything.  If you are able to do this this week, it is very likely this ends up in our next harvest. Let me know if there are questions.

**Comment by markpbaggett** [comment]
One last thing:  can you identify the set_id for southern places?  It probably starts with p15838coll.

**Comment by DonRichards** [comment]
Is this part of a Jira ticket? Does it need to be one?

**Comment by markpbaggett** [comment]
@DonRichards, I'm not sure what you mean. Yes, it needs to be done, but the DLTN doesn't use Jira.

**Comment by DonRichards** [comment]
Sorry, not sure what I was thinking.

**Comment by carolynfrunyon** [comment]
@markpbaggett, the OAI set for Southern Places is p15838coll4.

**Comment by kmiddlet** [comment]
Thanks, Carolyn, and sorry for not chiming in earlier. Our grant deadline has taken over my life.

**Comment by kmiddlet** [comment]
I have changed both collections to properly map the "collection" field to "Relation-is part of."  It's ok if it doesn't make this DPLA harvest. Just so it is in line for the following one.

**Comment by markpbaggett** [comment]
@kmiddlet, I'm grabbing this now.  No promises that this gets in to this harvest, but it will be there for the next. Once I've done this, I'll let you all know the Repox set name and that it's done if you want to take a look at it.

**Comment by kmiddlet** [comment]
Sounds good. Thanks!
