### ISSUE TITLE
Add new sets for June ingest

### ISSUE THREAD

**Issue by mlhale7** [DigitalLibraryofTennessee/DLTN_XSLT#181]
## Why are You Reporting an Issue

- [ ] Add New Set(s)
- [ ] Reingest Existing Set
- [ ] Report Problem with an Existing Set or XSL transform
- [ ] Discuss Issue or Ask Question
- [X] Add to repox and update sets.yml in https://github.com/DigitalLibraryofTennessee/dltn_ingestion3_config_generator

## New Set(s) / Reharvest Existing Set

UTK:
* utk_dabney (done)
* utk_tennessean (done)
* utk_torch (done)
* utk_yrb (done)

TSLA:
* tsla_p15138coll47 (done)

CMHF:
* cmhf_hatch (done)

**Comment by markpbaggett** [comment]
@mlhale7, just checking.  Are these utk sets ready to be harvested, or are we awaiting other work first?

**Comment by mlhale7** [comment]
@markpbaggett - I'm waiting until dabney is ingested into Islandora and available via OAI. I'll finish up the rest of the sets today before leaving.
