### ISSUE TITLE
Add p16877coll32 and Re-ingest p16877coll31 from UTC

### ISSUE THREAD

**Issue by carolynfrunyon** [DigitalLibraryofTennessee/DLTN_XSLT#195]
## Why are You Reporting an Issue

- [X] Add New Set(s)
- [X] Reingest Existing Set
- [ ] Report Problem with an Existing Set or XSL transform
- [ ] Discuss Issue or Ask Question
- [ ] Other

## New Set(s) / Reharvest Existing Set

Only required if you're requesting sets to be added or reharvested.

* p16877coll32
* p16877coll31

Thanks for all of your help!

**Comment by mlhale7** [comment]
@carolynfrunyon - coll31 has been updated and coll32 has been added to Repox. I'll close this ticket out once I've updated the IIIF manifests for these collections.
