### ISSUE TITLE
Adding items for September ingest

### ISSUE THREAD

**Issue by lboulie2** [DigitalLibraryofTennessee/DLTN_XSLT#200]
Reharvest Existing Set

https://digi.countrymusichalloffame.org/digital/collection/hatch3/search

https://digi.countrymusichalloffame.org/digital/collection/musicaudio/search

If you need me to send more info, or if I need to create this under a different heading--just let me know! 

Lee

**Comment by markpbaggett** [comment]
@lboulie2, this has been done.  The new records should show up in DPLA as soon as they have finished their processing.  Let us know if you have any questions.
