### ISSUE TITLE
UTC Harvest for March Ingest

### ISSUE THREAD

**Issue by carolynfrunyon** [DigitalLibraryofTennessee/DLTN_XSLT#215]
## Why are You Reporting an Issue

- [x] Add New Set(s)
- [x] Reingest Existing Set
- [ ] Report Problem with an Existing Set or XSL transform
- [ ] Discuss Issue or Ask Question
- [ ] Other

## New Set(s) / Reharvest Existing Set

Only required if you're requesting sets to be added or reharvested.

* p16877coll17
* p16877coll23
* p16877coll24
* p16877coll29
* p16877coll32
* p16877coll33

Thanks @mlhale7!

**Comment by mlhale7** [comment]
@carolynfrunyon - all of the sets to be updated have been updated. I'll close this out as soon as I see that coll33, your new set, has been added to OAI and is present in Repox.

**Comment by mlhale7** [comment]
@carolynfrunyon - checking in to mention that coll33 still hasn't been enabled. When it is updated, just let me know.

**Comment by carolynfrunyon** [comment]
Hi @mlhale7! Sorry for the delay. I've updated p16877coll33 to expose it for harvesting. Thanks!

**Comment by mlhale7** [comment]
@carolynfrunyon - I'm not seeing it yet, but I'll check back on this next week.

**Comment by mlhale7** [comment]
@carolynfrunyon - apologies to ask this again, but can you try enabling the collection for a second time? I'm still not seeing coll33 on http://cdm16877.contentdm.oclc.org/oai/oai.php?verb=ListSets

**Comment by carolynfrunyon** [comment]
@mlhale7, I'm so sorry I haven't been checking thoroughly. OCLC has been reporting some issues with indexing, but I think I've resolved the issues with p16877coll33.

**Comment by mlhale7** [comment]
Thanks @carolynfrunyon - the last set has been added to Repox :)
