### ISSUE TITLE
June Ingest

### ISSUE THREAD

**Issue by mlhale7** [DigitalLibraryofTennessee/DLTN_XSLT#227]
## Why are You Reporting an Issue

- [X] Add New Set(s)
- [X] Reingest Existing Set
- [ ] Report Problem with an Existing Set or XSL transform
- [ ] Discuss Issue or Ask Question
- [ ] Other

## New Set(s)

* utk_burford
* utk_hesler
* utk_jsevier
* utk_menbball
* utk_revwar
* utk_ramseyfp
* utk_tdh
* utk_womenbball
* utk_wwiioh
* utc_p16877coll34
* utc_p16877coll35
* utc_p16877coll36
* utc_p16877coll37
* utc_p16877coll38

## Reharvest

(Update Continuing Pubs for UTK)
* utk_alumnus 
* utk_comm
* utk_phoenix
* utk_playbills
* utk_torch

UTC
* utc_p16877coll8
* utc_p16877coll26
* utc_p16877coll27
* utc_p16877coll29
* utc_p16877coll30

**Comment by markpbaggett** [comment]
I pushed all XSLT and catalogs to the server earlier today.
