### ISSUE TITLE
Travis validity tests for "curled" sets are not working

### ISSUE THREAD

**Issue by markpbaggett** [DigitalLibraryofTennessee/DLTN_XSLT#232]
## Why are You Reporting an Issue

- [ ] Add New Set(s)
- [ ] Reingest Existing Set
- [ ] Report Problem with an Existing Set or XSL transform
- [ ] Discuss Issue or Ask Question
- [x] Other

## Other

Our tests for all curled sets are currently failing in Travis, but pass locally on the command line.  It's not clear at this point what's causing this. The error always looks like this:

`ASSERT:expected:<../working_directory/test.xml:1: parser error : Document is empty> but was:<../working_directory/test.xml validates>`

This could be a variety of things:  

1. Curl may be failing.
2. Something upstream in Travis has changed and it's missing a dependency.
3. Something else.

Since this passes locally, the only thing to really do is to create a new branch and change some of our failing tests to see which part is failing and address.

**Comment by markpbaggett** [comment]
So, I finally got around to looking at this.  For some reason, Travis is getting an HTTP 000 when it tries to connect to dpla.lib.utk.edu/repox.  I'm trying to read and understand what all could cause this.  Hopefully the server won't cause a similar response for other things (DPLA in general).

**Comment by CanOfBees** [comment]
@markpbaggett (sorry, I should know the answer to this but I don't) does travis try to connect to REPOX over ssl? Wondering if this could be related to the cert issues we've seen.

I know that speculation isn't very helpful, but this could be worth looking into.

**Comment by markpbaggett** [comment]
@CanOfBees 100% is.  I think it's that change that happened with SSL a few weeks ago.  Good thing:  we don't need to make any connections over HTTPs.  Funny:  our brains immediately went to this.  I'm going to put an explanation about this in the pull request.
