### ISSUE TITLE
Determine broken links for any DLTN objects in primary source sets or exhibits.

### ISSUE THREAD

**Issue by markpbaggett** [DigitalLibraryofTennessee/DLTN_XSLT#242]
## Why are You Reporting an Issue

- [ ] Add New Set(s)
- [ ] Reingest Existing Set
- [ ] Report Problem with an Existing Set or XSL transform
- [ ] Discuss Issue or Ask Question
- [ ] Other

## Potential Problem

Other hubs are having problems where links to objects in exhibits and primary source sets are broken.  This is due to the way dpla mints identifiers for ingestion 3 and local practices.  If our objects  have broken links currently, we get no traffic, and users do not know where an object is from.

**Comment by mlhale7** [comment]
This issue was resolved. Oddly enough, none of the links associated with DLTN were broken. Here's a link to the Primary Source Sets spreadsheet - https://docs.google.com/spreadsheets/d/1_C7mu741Fi1Lo8xmgbcEGSWAnTgZ7GUKCnmvMVLixWM/edit#gid=1024604898
