### ISSUE TITLE
Testing new sets for December ingest

### ISSUE THREAD

**Issue by mlhale7** [DigitalLibraryofTennessee/DLTN_XSLT#251]
## Why are You Reporting an Issue

- [ ] Add New Set(s)
- [ ] Reingest Existing Set
- [ ] Report Problem with an Existing Set or XSL transform
- [ ] Discuss Issue or Ask Question
- [X ] Other

## Sets to be Tested

Three new sets have been added to Repox following approval of new transform PRs. Before sharing with DPLA, we need to make sure that all three sets meet our requirements. The sets are:

* memphispublic_p16108coll5
* oakridge_p15388cdi
* oakridge_p16107coll3

**Comment by markpbaggett** [comment]
@mlhale7 all three of these look good, but we need to change the name for p1608coll5.

**Comment by mlhale7** [comment]
Thanks Mark. I wasn't sure if anything else needed to be done with the transform for that set since it is currently has a description of "delete". What needs to be done to rename this transform appropriately so that we can better identify it in the future? Otherwise I'm happy to change the set naming and delete the old entry for p16108coll5.
