### ISSUE TITLE
Add new sets

### ISSUE THREAD

**Issue by carolynfrunyon** [DigitalLibraryofTennessee/DLTN_XSLT#266]
## Why are You Reporting an Issue

- [x] Add New Set(s)
- [x] Reingest Existing Set
- [ ] Report Problem with an Existing Set or XSL transform
- [ ] Discuss Issue or Ask Question
- [ ] Other

## New Set(s) / Reharvest Existing Set

Only required if you're requesting sets to be added or reharvested.

* p16877coll8
* p16877coll33
* p16877coll34
* p16877coll38

## Problem with Set or Transform

I honestly don't remember what all has been harvested, but these sets have probably had a few recent additions or corrections. Sorry!

**Comment by mlhale7** [comment]
Thanks for this @carolynfrunyon. These sets have been updated. It looks like coll38 had 2 new records and coll34 had 11. We do definitely at least have all of our existing collections represented in Repox.
