### ISSUE TITLE
Crossroads Records Missing Rights

### ISSUE THREAD

**Issue by markpbaggett** [DigitalLibraryofTennessee/DLTN_XSLT#27]
## Why are You Reporting an Issue

- [ ] Add New Set(s)
- [ ] Reingest Existing Set
- [x] Report Problem with an Existing Set or XSL transform

## Problem with Set or Transform

These records from crossroads are missing a rights statement. Rather than applying one during remediation, we're ignoring these during a test prior to the merge to Repox process. Would it be possible to fix these?

1. [Interview with Brad McMillan](http://crossroads.rhodes.edu:9090/oaiprovider/oai/oai.cmd?verb=GetRecord&identifier=oai:crossroads.rhodes.edu:rds117346&metadataPrefix=oai_dc)
2. [Interview with Charles Dinkins](http://crossroads.rhodes.edu:9090/oaiprovider/oai/oai.cmd?verb=GetRecord&identifier=oai:crossroads.rhodes.edu:rds117341&metadataPrefix=oai_dc)
3. [Interview with Reverend James Jordan](http://crossroads.rhodes.edu:9090/oaiprovider/oai/oai.cmd?verb=GetRecord&identifier=oai:crossroads.rhodes.edu:rds117344&metadataPrefix=oai_dc)
4. [Interview with Eleanor and Ethel Terry Barham](http://crossroads.rhodes.edu:9090/oaiprovider/oai/oai.cmd?verb=GetRecord&identifier=oai:crossroads.rhodes.edu:rds117359&metadataPrefix=oai_dc)
5. [Interview with Mrs. Berta Radford](http://crossroads.rhodes.edu:9090/oaiprovider/oai/oai.cmd?verb=GetRecord&identifier=oai:crossroads.rhodes.edu:rds117362&metadataPrefix=oai_dc)
6. [Letter to Louis B. Nichols from Francis Fannon](http://crossroads.rhodes.edu:9090/oaiprovider/oai/oai.cmd?verb=GetRecord&identifier=oai:crossroads.rhodes.edu:rds117584&metadataPrefix=oai_dc)
7. [Cal Green Photograph](http://crossroads.rhodes.edu:9090/oaiprovider/oai/oai.cmd?verb=GetRecord&identifier=oai:crossroads.rhodes.edu:rds117820&metadataPrefix=oai_dc)
8. [Cancelled Checks #7](http://crossroads.rhodes.edu:9090/oaiprovider/oai/oai.cmd?verb=GetRecord&identifier=oai:crossroads.rhodes.edu:rds117971&metadataPrefix=oai_dc)
9. [1966 Cotton Makers' Jubilee Program](http://crossroads.rhodes.edu:9090/oaiprovider/oai/oai.cmd?verb=GetRecord&identifier=oai:crossroads.rhodes.edu:rds118233&metadataPrefix=oai_dc)
10. [Series on Memphis Music](http://crossroads.rhodes.edu:9090/oaiprovider/oai/oai.cmd?verb=GetRecord&identifier=oai:crossroads.rhodes.edu:rds118299&metadataPrefix=oai_dc)
11. [Music Forecast](http://crossroads.rhodes.edu:9090/oaiprovider/oai/oai.cmd?verb=GetRecord&identifier=oai:crossroads.rhodes.edu:rds118300&metadataPrefix=oai_dc)
12. [Letter from Ben Bridgewater to Klansman Gene Leath](http://crossroads.rhodes.edu:9090/oaiprovider/oai/oai.cmd?verb=GetRecord&identifier=oai:crossroads.rhodes.edu:rds118308&metadataPrefix=oai_dc)
13. [Firestone Mark Anniversary](http://crossroads.rhodes.edu:9090/oaiprovider/oai/oai.cmd?verb=GetRecord&identifier=oai:crossroads.rhodes.edu:rds118318&metadataPrefix=oai_dc)
14. [Letter from the Mountain Church to Unknown](http://crossroads.rhodes.edu:9090/oaiprovider/oai/oai.cmd?verb=GetRecord&identifier=oai:crossroads.rhodes.edu:rds118442&metadataPrefix=oai_dc)
15. [1948 Cotton Makers' Jubilee Program](http://crossroads.rhodes.edu:9090/oaiprovider/oai/oai.cmd?verb=GetRecord&identifier=oai:crossroads.rhodes.edu:rds118584&metadataPrefix=oai_dc)
16. [1952 Cotton Makers' Jubilee Program](http://crossroads.rhodes.edu:9090/oaiprovider/oai/oai.cmd?verb=GetRecord&identifier=oai:crossroads.rhodes.edu:rds118591&metadataPrefix=oai_dc)
17. [1934 Cotton Carnival Program](http://crossroads.rhodes.edu:9090/oaiprovider/oai/oai.cmd?verb=GetRecord&identifier=oai:crossroads.rhodes.edu:rds118552&metadataPrefix=oai_dc)
18. [Intelligence Report-The Philosopher of Racial Violence](http://crossroads.rhodes.edu:9090/oaiprovider/oai/oai.cmd?verb=GetRecord&identifier=oai:crossroads.rhodes.edu:rds118562&metadataPrefix=oai_dc)
19. [1971 Cotton Makers' Jubilee Program](http://crossroads.rhodes.edu:9090/oaiprovider/oai/oai.cmd?verb=GetRecord&identifier=oai:crossroads.rhodes.edu:rds118574&metadataPrefix=oai_dc)
20. [Letter to the Cotton Carnival Association from the family of Boss Crump](http://crossroads.rhodes.edu:9090/oaiprovider/oai/oai.cmd?verb=GetRecord&identifier=oai:crossroads.rhodes.edu:rds118576&metadataPrefix=oai_dc)
21. [Interview with Jesse Epps - Nov. 1969](http://crossroads.rhodes.edu:9090/oaiprovider/oai/oai.cmd?verb=GetRecord&identifier=oai:crossroads.rhodes.edu:rds118653&metadataPrefix=oai_dc)
22. [1940 Cotton Carnival Program](http://crossroads.rhodes.edu:9090/oaiprovider/oai/oai.cmd?verb=GetRecord&identifier=oai:crossroads.rhodes.edu:rds118610&metadataPrefix=oai_dc)
23. [1949 Cotton Makers' Jubilee Program](http://crossroads.rhodes.edu:9090/oaiprovider/oai/oai.cmd?verb=GetRecord&identifier=oai:crossroads.rhodes.edu:rds118611&metadataPrefix=oai_dc)
24. [Memphis World: Courtesy & Lives](http://crossroads.rhodes.edu:9090/oaiprovider/oai/oai.cmd?verb=GetRecord&identifier=oai:crossroads.rhodes.edu:rds58167&metadataPrefix=oai_dc)
25. [Crossroads Test](http://crossroads.rhodes.edu:9090/oaiprovider/oai/oai.cmd?verb=GetRecord&identifier=oai:crossroads.rhodes.edu:rds609&metadataPrefix=oai_dc)
26. [Hoxie Board Issues Challenge to Segregation Forces](http://crossroads.rhodes.edu:9090/oaiprovider/oai/oai.cmd?verb=GetRecord&identifier=oai:crossroads.rhodes.edu:rds689&metadataPrefix=oai_dc)
27. [Test 1](http://crossroads.rhodes.edu:9090/oaiprovider/oai/oai.cmd?verb=GetRecord&identifier=oai:crossroads.rhodes.edu:rds827&metadataPrefix=oai_dc)
28. [Interview with Dorothy Cox](http://crossroads.rhodes.edu:9090/oaiprovider/oai/oai.cmd?verb=GetRecord&identifier=oai:crossroads.rhodes.edu:rds984&metadataPrefix=oai_dc)

**Comment by bonefas** [comment]
Fixed all except #6, 24, 25 and 27.

**Comment by markpbaggett** [comment]
No longer a problem.
