### ISSUE TITLE
TSLA December Ingest

### ISSUE THREAD

**Issue by aimeesaunders** [DigitalLibraryofTennessee/DLTN_XSLT#275]
## Why are You Reporting an Issue

- [x] Add New Set(s)

## New Set(s) / Reharvest Existing Set

Only required if you're requesting sets to be added or reharvested.

p15138coll50

**Comment by mlhale7** [comment]
@aimeesaunders - thanks so much for opening this! I've added p15138coll50 and QA'd it. All the records are good to be ingested this Monday.
