### ISSUE TITLE
Crossroads Records Missing Identifiers

### ISSUE THREAD

**Issue by markpbaggett** [DigitalLibraryofTennessee/DLTN_XSLT#28]
## Why are You Reporting an Issue

- [ ] Add New Set(s)
- [ ] Reingest Existing Set
- [x] Report Problem with an Existing Set or XSL transform

## Problem with Set or Transform

These records from Crossroads to Freedom are missing dc:identifers with URIs.  Currently, we're removing these before they get to Repox, but it causes us more work. Would it be possible to fix these?  Let me know if there are any questions:

1. [Memphis World: Inside Memphis](http://crossroads.rhodes.edu:9090/oaiprovider/oai/oai.cmd?verb=GetRecord&identifier=oai:crossroads.rhodes.edu:rds117215&metadataPrefix=oai_dc)
2. [Memphis World: Citizens Demand More Action
PRESSURE ON NEGRO COUNCILMEN](http://crossroads.rhodes.edu:9090/oaiprovider/oai/oai.cmd?verb=GetRecord&identifier=oai:crossroads.rhodes.edu:rds117240&metadataPrefix=oai_dc)
3. [Memphis World: Morehouse Glee
Club Here April 8](http://crossroads.rhodes.edu:9090/oaiprovider/oai/oai.cmd?verb=GetRecord&identifier=oai:crossroads.rhodes.edu:rds117241&metadataPrefix=oai_dc)
4. [Memphis World: Memphians Baffled
As Snow Shuts Out
King's All-out March](http://crossroads.rhodes.edu:9090/oaiprovider/oai/oai.cmd?verb=GetRecord&identifier=oai:crossroads.rhodes.edu:rds117243&metadataPrefix=oai_dc)
5. [Memphis World: Students Lunch
With Businessmen](http://crossroads.rhodes.edu:9090/oaiprovider/oai/oai.cmd?verb=GetRecord&identifier=oai:crossroads.rhodes.edu:rds117233&metadataPrefix=oai_dc)
6. [Memphis World: Registration For
Two Seminars
Set For April 3](http://crossroads.rhodes.edu:9090/oaiprovider/oai/oai.cmd?verb=GetRecord&identifier=oai:crossroads.rhodes.edu:rds117238&metadataPrefix=oai_dc)
7. [Memphis World: 'Great Books' Big Hit With
Sixth Graders At Hanley](http://crossroads.rhodes.edu:9090/oaiprovider/oai/oai.cmd?verb=GetRecord&identifier=oai:crossroads.rhodes.edu:rds117251&metadataPrefix=oai_dc)
8. [Memphis World: Rats And Cats Eat
Better than we Do,
Says One Striker](http://crossroads.rhodes.edu:9090/oaiprovider/oai/oai.cmd?verb=GetRecord&identifier=oai:crossroads.rhodes.edu:rds117257&metadataPrefix=oai_dc)
9. [Memphis World: Dr. Williamson To
Present Paper](http://crossroads.rhodes.edu:9090/oaiprovider/oai/oai.cmd?verb=GetRecord&identifier=oai:crossroads.rhodes.edu:rds117265&metadataPrefix=oai_dc)

**Comment by bonefas** [comment]
Robert scripted the ingestion process for article level objects, and we don't have edit access to the DC. I could try to re-ingest these issues. 

What's weird about all these is that the identifier **is** in the header but didn't write to the DC identifier field.

**Comment by robert-patrick-waltz** [comment]
This is the DC from the record titled "Memphis World: Inside Memphis"

http://crossroads.rhodes.edu:9090/fedora/get/rds:117215/DC

The dublin core does not show any identifiers

Here is another record that appears good:
http://crossroads.rhodes.edu:9090/fedora/get/rds:33778/DC

The dublin core does show identifiers:

> <dc:identifier>rds:33778</dc:identifier>
> <dc:identifier>http://www.crossroadstofreedom.org/view.player?pid=rds:33778</dc:identifier>


For those objects missing dc:identifiers, it should be fairly easy to go into 
either Elated (assuming it is operational), or by using the fedoraAdmin cmdline
tool to change the DC.

**Comment by markpbaggett** [comment]
Yeah, to be clear, there are only 9 records out of the 116000 plus records that appear to have this problem, and they are listed above. @bonefas, I think Robert thinks we might be able to assist with this if you are okay with that (fixing them on your end).  Are you cool with that?

**Comment by robert-patrick-waltz** [comment]
I don't seem to have access after all.

**Comment by bonefas** [comment]
Thanks, y'all. We bypassed Elated with article-level objects, so those need to be edited directly in Fedora with the command line tool, as you suggest. I can re-acquaint myself with this. 

This is also true of the 4 records with missing rights info that I haven't fixed - they aren't in Elated, and need to be edited in Fedora. 

@robert-patrick-waltz , what kind of access are you needing?

**Comment by robert-patrick-waltz** [comment]
I believe I need vpn access to begin with. I believe there are 3 machines I had access to when working before. 1) The web and app server on which the crossroads fedora instance is running. 2) The server elated is running on 3) the svn repo for rhodes.

**Comment by markpbaggett** [comment]
No longer a problem.
