### ISSUE TITLE
Reharvest 2 UTC Sets

### ISSUE THREAD

**Issue by carolynfrunyon** [DigitalLibraryofTennessee/DLTN_XSLT#288]
## Why are You Reporting an Issue
- [x] Reingest Existing Set

## New Set(s) / Reharvest Existing Set

Only required if you're requesting sets to be added or reharvested.

*p16877coll39
*p16877coll9

Thank you! I appreciate you keeping us current in DPLA!

**Comment by mlhale7** [comment]
Thanks for this @carolynfrunyon. I appreciate that you continue to send in new sets! These updates have been made. This isn't an issue for ingest, but I wanted to note that only 2014 of the 2215 records in coll9 have a rightsHolder (but that's not a required DPLA field). This could be exactly what you expect, but I wanted to mention it just in case.

You might have heard from Noah, but just as an fyi, our next ingest will be in June (date TBA). I'm going to be on leave from April to the start of August, but I do plan to work some hours in June to make sure the ingest then is successful. Feel free to add any other new sets ahead of June - I may just be slow to respond!
