### ISSUE TITLE
Harvest p16877coll45, p16877coll47, and p16877coll48

### ISSUE THREAD

**Issue by carolynfrunyon** [DigitalLibraryofTennessee/DLTN_XSLT#294]
## Why are You Reporting an Issue

- [x] Add New Set(s)
- [ ] Reingest Existing Set
- [ ] Report Problem with an Existing Set or XSL transform
- [ ] Discuss Issue or Ask Question
- [ ] Other

## New Set(s) / Reharvest Existing Set

Only required if you're requesting sets to be added or reharvested.

* p16877coll45
* p16877coll47
* p16877coll48

## Problem with Set or Transform

Only required if reporting problem with metadata or transform.

* Please report any information to make finding this issue possible.

## Discuss Issue or Ask Question

Thank you for keeping us up-to-date!

**Comment by mlhale7** [comment]
Thanks for this @carolynfrunyon! All of these collections meet our standards and have been added for the ingest.
