### ISSUE TITLE
New set from UTC

### ISSUE THREAD

**Issue by mpcopeland** [DigitalLibraryofTennessee/DLTN_XSLT#307]
## Why are You Reporting an Issue

- [x] Add New Set(s)
- [ ] Reingest Existing Set
- [ ] Report Problem with an Existing Set or XSL transform
- [ ] Discuss Issue or Ask Question
- [ ] Other

## New Set(s) / Reharvest Existing Set

Only required if you're requesting sets to be added or reharvested.

* p16877coll55

Thank you!

**Comment by mlhale7** [comment]
Thanks for this @mpcopeland. I've added this set.

Random aside, but I was looking at your collections online and I noticed that all of the values in your facets are automatically lowercased? Feel free to ignore this comment if this is intentionally done to simply normalize values (I just haven't seen this done before).
