### ISSUE TITLE
New Records from Special Collections

### ISSUE THREAD

**Issue by carolynfrunyon** [DigitalLibraryofTennessee/DLTN_XSLT#318]
## Why are You Reporting an Issue

- [x] Add New Set(s)
- [ ] Reingest Existing Set
- [ ] Report Problem with an Existing Set or XSL transform
- [ ] Discuss Issue or Ask Question
- [ ] Other

## New Set(s) / Reharvest Existing Set

Only required if you're requesting sets to be added or reharvested.

*p16877coll56
* p16877coll57
* p16877coll58
* p16877coll60

## Discuss Issue or Ask Question

Thank you for keeping our records updated!

**Comment by mlhale7** [comment]
Thanks for this @carolynfrunyon. These sets have all the required fields. I do have one question on coll57. Both UTC and the public library are listed as the publisher. Would you like the Chattanooga Public Library to be listed as the contributing partner as well as UTC? Also, I wanted to ensure that none of this content is available through their digital collections also? We added Chattanooga Public as a partner in Dec 2023 - https://dp.la/search?q=Chattanooga&provider=%22Chattanooga+Public+Library%22&page=1

**Comment by carolynfrunyon** [comment]
Hi at @mlhale7! Collections in which CHP and UTC are listed as the publisher are typically the collections of the former Chattanooga History Center. These collections are co-owned by UTC and CPL and are distinct from the holdings CPL is pushing from their Digital Collections hosted at https://collections.chattlibrary.org/s/localhistory/page/home. There is likely to be some accidental duplication between our holdings, because we find photos taken by local photographers like Delmont Wilson, Bob Sherril, etc. across many collections. But, we're not conscientiously duplicating effort.

**Comment by mlhale7** [comment]
@carolynfrunyon - thanks for this. It seems accurate then to keep UTC as the sole contributor (that can be faceted upon in the DPLA interface). I don't think any edits/special treatment are needed for this set given what you shared.

I'm not worried about occasional duplication (we definitely have some between UTK and Knox Public).
