### ISSUE TITLE
TSLA tfd missing rights statements

### ISSUE THREAD

**Issue by markpbaggett** [DigitalLibraryofTennessee/DLTN_XSLT#32]
## Why are You Reporting an Issue

- [ ] Add New Set(s)
- [ ] Reingest Existing Set
- [x] Report Problem with an Existing Set or XSL transform

## Problem with Set or Transform

This is a subticket of [Issue 31](https://github.com/DigitalLibraryofTennessee/DLTN_XSLT/issues/31).

Currently, all of these records that are going to DPLA are having a rights statement automatically applied; this happened when we first went to DPLA, and we've never had time to fix this. Luckily, the rights statement being applied is pretty generic and is taken from TSLA. We'd like to work on this for August, but some of this could potentially be addressed by TSLA. Let me know what you think is doable, and we can come up with a plan for summer.

Potential ideas / solutions:

1. We drop the set altogether.
2. TSLA fixes these in ContentDM and we reingest.
3. UTK drops the rights transform and we fix by harvesting into BaseX and running a transform to determine if it has rights before it goes into our Aggregator.

Here are the records missing rights from this set:

1. [Tennessee Constitution, 1796](http://cdm15138.contentdm.oclc.org/oai/oai.php?verb=GetRecord&identifier=oai:cdm15138.contentdm.oclc.org:tfd/421&metadataPrefix=oai_dc)
2. [Cumberland Compact](http://cdm15138.contentdm.oclc.org/oai/oai.php?verb=GetRecord&identifier=oai:cdm15138.contentdm.oclc.org:tfd/460&metadataPrefix=oai_dc)
3. [Watauga Purchase (Old Book A)](http://cdm15138.contentdm.oclc.org/oai/oai.php?verb=GetRecord&identifier=oai:cdm15138.contentdm.oclc.org:tfd/466&metadataPrefix=oai_dc)
4. [King George III's Proclamation of 1763](http://cdm15138.contentdm.oclc.org/oai/oai.php?verb=GetRecord&identifier=oai:cdm15138.contentdm.oclc.org:tfd/488&metadataPrefix=oai_dc)
5. [Tennessee Constitution, 1834](http://cdm15138.contentdm.oclc.org/oai/oai.php?verb=GetRecord&identifier=oai:cdm15138.contentdm.oclc.org:tfd/495&metadataPrefix=oai_dc)
6. [Tennessee Civil and Military Commission Book, Volume 1](http://cdm15138.contentdm.oclc.org/oai/oai.php?verb=GetRecord&identifier=oai:cdm15138.contentdm.oclc.org:tfd/523&metadataPrefix=oai_dc)
7. [An Ordinance for Circumscribing the Counties of Greene and Hawkins and Laying out Two New Counties](http://cdm15138.contentdm.oclc.org/oai/oai.php?verb=GetRecord&identifier=oai:cdm15138.contentdm.oclc.org:tfd/528&metadataPrefix=oai_dc)
8. [An Act to Cut and Clear a Waggon Road to the Settlements on the Cumberland River in the Mero District](http://cdm15138.contentdm.oclc.org/oai/oai.php?verb=GetRecord&identifier=oai:cdm15138.contentdm.oclc.org:tfd/535&metadataPrefix=oai_dc)
9. [Act for the Purpose of Raising a Fund for Erecting a District Jail and Stocks in the Town of Nashville in the Mero District](http://cdm15138.contentdm.oclc.org/oai/oai.php?verb=GetRecord&identifier=oai:cdm15138.contentdm.oclc.org:tfd/540&metadataPrefix=oai_dc)
10. [An Act for the Enumeration of the Inhabitants of the Territory of the United States of America South of the River Ohio](http://cdm15138.contentdm.oclc.org/oai/oai.php?verb=GetRecord&identifier=oai:cdm15138.contentdm.oclc.org:tfd/550&metadataPrefix=oai_dc)
11. [An Act for the admission of the State of Tennessee into the Union](http://cdm15138.contentdm.oclc.org/oai/oai.php?verb=GetRecord&identifier=oai:cdm15138.contentdm.oclc.org:tfd/553&metadataPrefix=oai_dc)
12. [Governor Sevier's Address to the first General Assembly](http://cdm15138.contentdm.oclc.org/oai/oai.php?verb=GetRecord&identifier=oai:cdm15138.contentdm.oclc.org:tfd/556&metadataPrefix=oai_dc)
13. [1870 Constitution](http://cdm15138.contentdm.oclc.org/oai/oai.php?verb=GetRecord&identifier=oai:cdm15138.contentdm.oclc.org:tfd/584&metadataPrefix=oai_dc)
14. [Donelson Journal](http://cdm15138.contentdm.oclc.org/oai/oai.php?verb=GetRecord&identifier=oai:cdm15138.contentdm.oclc.org:tfd/600&metadataPrefix=oai_dc)
15. [1818 Letter from Cherokee chiefs to Gov. McMinn](http://cdm15138.contentdm.oclc.org/oai/oai.php?verb=GetRecord&identifier=oai:cdm15138.contentdm.oclc.org:tfd/616&metadataPrefix=oai_dc)

**Comment by jrandlestsla** [comment]
I have done a global find and replace for rights in this collection. Let me know if there are still any outliers.

**Comment by markpbaggett** [comment]
This one looks good to go too. 0 records missing rights statements.

I'm going to leave this open as a reminder to pull in your new ones, but we should be good.

**Comment by markpbaggett** [comment]
This one has been reharvested and tested.  Thanks for working on this.
