### ISSUE TITLE
TSLA p15138coll6 records missing rights

### ISSUE THREAD

**Issue by markpbaggett** [DigitalLibraryofTennessee/DLTN_XSLT#36]
## Why are You Reporting an Issue

- [ ] Add New Set(s)
- [ ] Reingest Existing Set
- [x] Report Problem with an Existing Set or XSL transform

## Problem with Set or Transform
This is a subticket of [Issue 31](https://github.com/DigitalLibraryofTennessee/DLTN_XSLT/issues/31).

Currently, all of these records that are going to DPLA are having a rights statement automatically applied; this happened when we first went to DPLA, and we've never had time to fix this. Luckily, the rights statement being applied is pretty generic and is taken from TSLA. We'd like to work on this for August, but some of this could potentially be addressed by TSLA. Let me know what you think is doable, and we can come up with a plan for summer.

Potential ideas / solutions:

1. We drop the set altogether.
2. TSLA fixes these in ContentDM and we reingest.
3. UTK drops the rights transform and we fix by harvesting into BaseX and running a transform to determine if it has rights before it goes into our Aggregator.

Here are the records missing rights from this set:

1. [Commission of John Parham III](http://cdm15138.contentdm.oclc.org/oai/oai.php?verb=GetRecord&identifier=oai:cdm15138.contentdm.oclc.org:p15138coll6/9276&metadataPrefix=oai_dc)
2. [Tintype of James Lafayette Parham](http://cdm15138.contentdm.oclc.org/oai/oai.php?verb=GetRecord&identifier=oai:cdm15138.contentdm.oclc.org:p15138coll6/9277&metadataPrefix=oai_dc)
3. [Civil War dug relics from various locations around Bledsoe County, Tennessee](http://cdm15138.contentdm.oclc.org/oai/oai.php?verb=GetRecord&identifier=oai:cdm15138.contentdm.oclc.org:p15138coll6/9278&metadataPrefix=oai_dc)
4. [Bill of sale for a slave woman in Bledsoe County](http://cdm15138.contentdm.oclc.org/oai/oai.php?verb=GetRecord&identifier=oai:cdm15138.contentdm.oclc.org:p15138coll6/9279&metadataPrefix=oai_dc)
5. [Certificate to carry (fire) arms](http://cdm15138.contentdm.oclc.org/oai/oai.php?verb=GetRecord&identifier=oai:cdm15138.contentdm.oclc.org:p15138coll6/9280&metadataPrefix=oai_dc)

**Comment by jrandlestsla** [comment]
I have done a global find and replace for rights in this collection. Let me know if there are still any outliers.

**Comment by markpbaggett** [comment]
Cool!  I'll reharvest these and let you know. Thanks!

**Comment by markpbaggett** [comment]
Jennifer, this one looks good to go.  When I look for records missing rights I get 0 results, and when I look for unique rights statements, I only get this one:

> While TSLA houses an item, it does not necessarily hold the copyright on the item, nor may it be able to determine if the item is still protected under current copyright law. Users are solely responsible for determining the existence of such instances and for obtaining any other permissions and paying associated fees, that may be necessary for the intended use.

I'm going to leave this open for now (until I do a full reharvest), but I think we should be good.  Thanks again.

**Comment by markpbaggett** [comment]
@jrandlestsla sorry for the delays.  This has been reharvested and will appear in DPLA after our next ingest.
