### ISSUE TITLE
Ghost Records from Crossroads that Aren't OAI Compliant

### ISSUE THREAD

**Issue by markpbaggett** [DigitalLibraryofTennessee/DLTN_XSLT#37]
## Why are You Reporting an Issue

- [ ] Add New Set(s)
- [ ] Reingest Existing Set
- [x] Report Problem with an Existing Set or XSL transform

## Problem with Set or Transform

This may or may not be a problem, but I wanted to report it while I was thinking about it.  We were creating the same issue for DPLA at UTK, and they thought it was worth fixing.  There are 7 OAI records from Crossroads to Freedom that aren't OAI Compliant.  That's because they have empty /metadata and header/identifier sections.  Is it possible to remove these altogether or mark as deleted? If it's useful, I'd be happy to write something to show where these are / what the look like in the response.  If it's a lot of trouble, let's just say so and ignore it altogether. This doesn't cause problems for us according to our current methods.

**Comment by bonefas** [comment]
@markpbaggett I'd love to know more about where these are and what they look like. 

We definitely have some weird "test" records that bypassed our admin system (Elated) and somehow ended up published to the OAI feed. But maybe some of these are in Elated, in which case I may be able to delete them.

**Comment by markpbaggett** [comment]
@bonefas,  absolutely.  I'm a little behind right now, but I'll try to write something tomorrow that can say specifically where you could see these when passing a response token.  It's tough because they have an empty metadata node and an empty oai identifier in the header information.

Again, it's really not a big deal for us currently. Our technology simply ignores these. I only brought it up because Repox with our XSLT was doing something similar (keep an oai record with an empty metadata section) and this was causing problems for DPLA's stack.

**Comment by markpbaggett** [comment]
No longer a problem now that we are pulling from dlynx.
