### ISSUE TITLE
ContentDM and HTTPS?

### ISSUE THREAD

**Issue by markpbaggett** [DigitalLibraryofTennessee/DLTN_XSLT#45]
## Why are You Reporting an Issue

- [ ] Add New Set(s)
- [ ] Reingest Existing Set
- [ ] Report Problem with an Existing Set or XSL transform
- [ ] Discuss Issue or Ask Question
- [x] Other

## Discuss Issue or Ask Question

In preparation for all of the stuff with the new version of Google Chrome and HTTPS Everywhere, I'm wondering if we at UTK need to be prepared for people switching to HTTPS.  Is this on anyone's immediate roadmap?  The links we provide to DPLA all start with HTTP, so users who discover the content in DPLA would access it over HTTP.  If they did a search within your system after they were referred and ContentDM doesn't plan to use something like mod rewrite, users are going to get an "insecure site" message.

Is there anything you all know of between now and October 17 that we need to be prepared for? Are you aware of OCLC's response?

Thanks for any help / heads up you can provide.  We'll need to think about whether we need to reharvest or handle this within transformations.

## Interested Parties

@carolynfrunyon @stevendshelton @kmiddlet @jrandlestsla

**Comment by carolynfrunyon** [comment]
@stevendshelton had some concerns about this as it doesn't appear to be on OCLC's roadmap for CONTENTdm. He can definitely chime in with a more informed response about this than I.

**Comment by markpbaggett** [comment]
Interesting.  I'm surprised they aren't prepared for this.  We have several legacy systems we're trying to migrate away from that are going to be affected for a short time.  Anyway,I'll take a look at ContentDM with Chrome beta, but it's good to know we won't have to rush to deal with this as a service hub.

**Comment by jrandlestsla** [comment]
In the July release notes for the responsive version, they do mention HTTPS support. I don't know that it applies to the 6.1 version, which we are still on. 

https://www.oclc.org/content/dam/support/release-notes/contentdm/2017/contentdm_release_notes_2017-07.pdf

**Comment by markpbaggett** [comment]
Closing this.
