### ISSUE TITLE
Coll22 - Permission to Add

### ISSUE THREAD

**Issue by mlhale7** [DigitalLibraryofTennessee/DLTN_XSLT#47]
## Why are You Reporting an Issue

- Add New Set(s)

## New Set(s) / Reharvest Existing Set

* utc_p16877_coll22_qdc (Cold War Oral Histories)

## Discuss Issue or Ask Question

* Let us know if it's okay for us to add this new set to DPLA.

**Comment by markpbaggett** [comment]
@carolynfrunyon, we're wondering if we should be including **p16877_coll22** to DPLA.  We almost did this on accident, but we're wondering if we should have been adding it all along.  Let us know what you prefer.

**Comment by carolynfrunyon** [comment]
Oh yeah! Let's add that! All of the collections in our CONTENTdm repository are fair game!

**Comment by markpbaggett** [comment]
Closing.
