### ISSUE TITLE
TSLA Sets for Jennifer Randles

### ISSUE THREAD

**Issue by markpbaggett** [DigitalLibraryofTennessee/DLTN_XSLT#48]
## Why are You Reporting an Issue

Adding this so we don't forget.

- [X] Add New Set(s)
- [X] Reingest Existing Set
- [ ] Report Problem with an Existing Set or XSL transform
- [ ] Discuss Issue or Ask Question
- [ ] Other

## New Set(s) / Reharvest Existing Set

Only required if you're requesting sets to be added or reharvested.

- p15138coll42
- p15138coll41
- p15138coll38
- p15138coll40
- p15138coll39
- p15138coll37
- p15138coll36
- p15138coll33
- p15138coll34
- p15138coll32
- p15138coll29
- p15138coll27
- p15138coll26
- p15138coll24
- p15138coll25
- p15138coll2
- p15138coll23
- johnson
- Strickland
- p15138coll18
- p15138coll14
- p15138coll35
- Mustard
- Fisk
- stateguard
- bernhardt
- mckenneyHal

**Comment by markpbaggett** [comment]
@jrandlestsla, adding this here so we don't forget.  If it's okay, this is what I'd like to do:

1. Start by looking at sets we don't have.
2. Review feed
3. Develop and metadata mapping (share problems)
4. Write transform
5. Harvest the data
6. Revisit existing sets.

Is this cool with you?

**Comment by jrandlestsla** [comment]
Thank you! That works for me. Should I put the list of new collections here?

**Comment by mlhale7** [comment]
@jrandlestsla - The sets p15138coll35 and stateguard don't currently exist as sets in OAI. Is there anything in ContentDM you can update?

**Comment by jrandlestsla** [comment]
I will check into it. I am running into some odd errors and can't figure out where to fix them. I will have to call them and figure it out.

Can I also add this collection to the list? It is our newest. p15138coll42

**Comment by mlhale7** [comment]
Thanks @jrandlestsla! The newest set has been added to the list. Let us know if you discover anything about the other two sets.

**Comment by mlhale7** [comment]
@jrandlestsla - It looks like coll35 has been added to OAI. Unfortunately the new set you mentioned (p15138coll42) still is not accessible through OAI. Let me know if you are able to update this.

**Comment by jrandlestsla** [comment]
Can you check now? It should be fixed.

**Comment by jrandlestsla** [comment]
Were you able to get the OAI feed for coll42?

**Comment by markpbaggett** [comment]
@jrandlestsla I still don see it.  Here are the ones we can see:

http://cdm15138.contentdm.oclc.org/oai/oai.php?verb=ListSets

**Comment by jrandlestsla** [comment]
Ok, I changed a setting and I think it's showing up at the link on the bottom.

**Comment by mlhale7** [comment]
Thanks Jennifer! It is now present and we'll add it.

**Comment by jrandlestsla** [comment]
Thank you! Sorry about all this. There seems to be about 5 places I have to change settings to get collections to sync in OAI and Worldcat.

**Comment by mlhale7** [comment]
No problem - I apologize for not following up sooner.

**Comment by jrandlestsla** [comment]
Great, thank you! No problem- I know how these things fall through the cracks.

**Comment by mlhale7** [comment]
Hi @jrandlestsla. We went through the three remaining sets today. We were able to successfully add p15138coll26 and bernhardt. The third set, p15138coll23, has some rights issues that need to be addressed. A total of 46 items have no rights statement.

Below is a complete list of these items (by identifier/link) that need to be updated. Let us know if you find the time to add rights for these and we can try to ingest them again.

1. [http://cdm15138.contentdm.oclc.org/cdm/ref/collection/p15138coll23/id/9871](http://cdm15138.contentdm.oclc.org/cdm/ref/collection/p15138coll23/id/9871)
2. [http://cdm15138.contentdm.oclc.org/cdm/ref/collection/p15138coll23/id/9872](http://cdm15138.contentdm.oclc.org/cdm/ref/collection/p15138coll23/id/9872)
3. [http://cdm15138.contentdm.oclc.org/cdm/ref/collection/p15138coll23/id/9873](http://cdm15138.contentdm.oclc.org/cdm/ref/collection/p15138coll23/id/9873)
4. [http://cdm15138.contentdm.oclc.org/cdm/ref/collection/p15138coll23/id/9874](http://cdm15138.contentdm.oclc.org/cdm/ref/collection/p15138coll23/id/9874)
5. [http://cdm15138.contentdm.oclc.org/cdm/ref/collection/p15138coll23/id/9875](http://cdm15138.contentdm.oclc.org/cdm/ref/collection/p15138coll23/id/9875)
6. [http://cdm15138.contentdm.oclc.org/cdm/ref/collection/p15138coll23/id/9876](http://cdm15138.contentdm.oclc.org/cdm/ref/collection/p15138coll23/id/9876)
7. [http://cdm15138.contentdm.oclc.org/cdm/ref/collection/p15138coll23/id/9877](http://cdm15138.contentdm.oclc.org/cdm/ref/collection/p15138coll23/id/9877)
8. [http://cdm15138.contentdm.oclc.org/cdm/ref/collection/p15138coll23/id/9878](http://cdm15138.contentdm.oclc.org/cdm/ref/collection/p15138coll23/id/9878)
9. [http://cdm15138.contentdm.oclc.org/cdm/ref/collection/p15138coll23/id/9879](http://cdm15138.contentdm.oclc.org/cdm/ref/collection/p15138coll23/id/9879)
10. [http://cdm15138.contentdm.oclc.org/cdm/ref/collection/p15138coll23/id/9880](http://cdm15138.contentdm.oclc.org/cdm/ref/collection/p15138coll23/id/9880)
11. [http://cdm15138.contentdm.oclc.org/cdm/ref/collection/p15138coll23/id/9881](http://cdm15138.contentdm.oclc.org/cdm/ref/collection/p15138coll23/id/9881)
12. [http://cdm15138.contentdm.oclc.org/cdm/ref/collection/p15138coll23/id/9882](http://cdm15138.contentdm.oclc.org/cdm/ref/collection/p15138coll23/id/9882)
13. [http://cdm15138.contentdm.oclc.org/cdm/ref/collection/p15138coll23/id/9883](http://cdm15138.contentdm.oclc.org/cdm/ref/collection/p15138coll23/id/9883)
14. [http://cdm15138.contentdm.oclc.org/cdm/ref/collection/p15138coll23/id/9884](http://cdm15138.contentdm.oclc.org/cdm/ref/collection/p15138coll23/id/9884)
15. [http://cdm15138.contentdm.oclc.org/cdm/ref/collection/p15138coll23/id/9885](http://cdm15138.contentdm.oclc.org/cdm/ref/collection/p15138coll23/id/9885)
16. [http://cdm15138.contentdm.oclc.org/cdm/ref/collection/p15138coll23/id/9886](http://cdm15138.contentdm.oclc.org/cdm/ref/collection/p15138coll23/id/9886)
17. [http://cdm15138.contentdm.oclc.org/cdm/ref/collection/p15138coll23/id/9887](http://cdm15138.contentdm.oclc.org/cdm/ref/collection/p15138coll23/id/9887)
18. [http://cdm15138.contentdm.oclc.org/cdm/ref/collection/p15138coll23/id/9888](http://cdm15138.contentdm.oclc.org/cdm/ref/collection/p15138coll23/id/9888)
19. [http://cdm15138.contentdm.oclc.org/cdm/ref/collection/p15138coll23/id/9889](http://cdm15138.contentdm.oclc.org/cdm/ref/collection/p15138coll23/id/9889)
20. [http://cdm15138.contentdm.oclc.org/cdm/ref/collection/p15138coll23/id/9890](http://cdm15138.contentdm.oclc.org/cdm/ref/collection/p15138coll23/id/9890)
21. [http://cdm15138.contentdm.oclc.org/cdm/ref/collection/p15138coll23/id/9891](http://cdm15138.contentdm.oclc.org/cdm/ref/collection/p15138coll23/id/9891)
22. [http://cdm15138.contentdm.oclc.org/cdm/ref/collection/p15138coll23/id/9892](http://cdm15138.contentdm.oclc.org/cdm/ref/collection/p15138coll23/id/9892)
23. [http://cdm15138.contentdm.oclc.org/cdm/ref/collection/p15138coll23/id/9893](http://cdm15138.contentdm.oclc.org/cdm/ref/collection/p15138coll23/id/9893)
24. [http://cdm15138.contentdm.oclc.org/cdm/ref/collection/p15138coll23/id/9894](http://cdm15138.contentdm.oclc.org/cdm/ref/collection/p15138coll23/id/9894)
25. [http://cdm15138.contentdm.oclc.org/cdm/ref/collection/p15138coll23/id/9895](http://cdm15138.contentdm.oclc.org/cdm/ref/collection/p15138coll23/id/9895)
26. [http://cdm15138.contentdm.oclc.org/cdm/ref/collection/p15138coll23/id/9896](http://cdm15138.contentdm.oclc.org/cdm/ref/collection/p15138coll23/id/9896)
27. [http://cdm15138.contentdm.oclc.org/cdm/ref/collection/p15138coll23/id/9897](http://cdm15138.contentdm.oclc.org/cdm/ref/collection/p15138coll23/id/9897)
28. [http://cdm15138.contentdm.oclc.org/cdm/ref/collection/p15138coll23/id/9898](http://cdm15138.contentdm.oclc.org/cdm/ref/collection/p15138coll23/id/9898)
29. [http://cdm15138.contentdm.oclc.org/cdm/ref/collection/p15138coll23/id/9899](http://cdm15138.contentdm.oclc.org/cdm/ref/collection/p15138coll23/id/9899)
30. [http://cdm15138.contentdm.oclc.org/cdm/ref/collection/p15138coll23/id/9900](http://cdm15138.contentdm.oclc.org/cdm/ref/collection/p15138coll23/id/9900)
31. [http://cdm15138.contentdm.oclc.org/cdm/ref/collection/p15138coll23/id/9901](http://cdm15138.contentdm.oclc.org/cdm/ref/collection/p15138coll23/id/9901)
32. [http://cdm15138.contentdm.oclc.org/cdm/ref/collection/p15138coll23/id/9902](http://cdm15138.contentdm.oclc.org/cdm/ref/collection/p15138coll23/id/9902)
33. [http://cdm15138.contentdm.oclc.org/cdm/ref/collection/p15138coll23/id/9903](http://cdm15138.contentdm.oclc.org/cdm/ref/collection/p15138coll23/id/9903)
34. [http://cdm15138.contentdm.oclc.org/cdm/ref/collection/p15138coll23/id/9904](http://cdm15138.contentdm.oclc.org/cdm/ref/collection/p15138coll23/id/9904)
35. [http://cdm15138.contentdm.oclc.org/cdm/ref/collection/p15138coll23/id/9905](http://cdm15138.contentdm.oclc.org/cdm/ref/collection/p15138coll23/id/9905)
36. [http://cdm15138.contentdm.oclc.org/cdm/ref/collection/p15138coll23/id/9906](http://cdm15138.contentdm.oclc.org/cdm/ref/collection/p15138coll23/id/9906)
37. [http://cdm15138.contentdm.oclc.org/cdm/ref/collection/p15138coll23/id/9907](http://cdm15138.contentdm.oclc.org/cdm/ref/collection/p15138coll23/id/9907)
38. [http://cdm15138.contentdm.oclc.org/cdm/ref/collection/p15138coll23/id/9908](http://cdm15138.contentdm.oclc.org/cdm/ref/collection/p15138coll23/id/9908)
39. [http://cdm15138.contentdm.oclc.org/cdm/ref/collection/p15138coll23/id/9909](http://cdm15138.contentdm.oclc.org/cdm/ref/collection/p15138coll23/id/9909)
40. [http://cdm15138.contentdm.oclc.org/cdm/ref/collection/p15138coll23/id/9910](http://cdm15138.contentdm.oclc.org/cdm/ref/collection/p15138coll23/id/9910)
41. [http://cdm15138.contentdm.oclc.org/cdm/ref/collection/p15138coll23/id/9911](http://cdm15138.contentdm.oclc.org/cdm/ref/collection/p15138coll23/id/9911)
42. [http://cdm15138.contentdm.oclc.org/cdm/ref/collection/p15138coll23/id/9912](http://cdm15138.contentdm.oclc.org/cdm/ref/collection/p15138coll23/id/9912)
43. [http://cdm15138.contentdm.oclc.org/cdm/ref/collection/p15138coll23/id/9913](http://cdm15138.contentdm.oclc.org/cdm/ref/collection/p15138coll23/id/9913)
44. [http://cdm15138.contentdm.oclc.org/cdm/ref/collection/p15138coll23/id/9914](http://cdm15138.contentdm.oclc.org/cdm/ref/collection/p15138coll23/id/9914)
45. [http://cdm15138.contentdm.oclc.org/cdm/ref/collection/p15138coll23/id/9915](http://cdm15138.contentdm.oclc.org/cdm/ref/collection/p15138coll23/id/9915)
46. [http://cdm15138.contentdm.oclc.org/cdm/ref/collection/p15138coll23/id/9916](http://cdm15138.contentdm.oclc.org/cdm/ref/collection/p15138coll23/id/9916)

**Comment by jrandlestsla** [comment]
Thanks! That is exciting. Those are all metadata-only records, which I don't want in DPLA anyway. Can we ingest a set without every item having a rights statement, or do all rights statements have to be complete to ingest anything from a collection?

**Comment by mlhale7** [comment]
Because we can't restrict individual items from a set, all rights statements have to be complete for us to ingest. Rights are a required field for DPLA. If there's any way to separate these items out into a separate set, we would be able to take the rest of the records. Let me know if you have ideas or questions.

**Comment by mlhale7** [comment]
Hi @jrandlestsla - is it okay for me to close this issue for now? Let us know if you want to do anything with p15138coll23 in the future and we'll open a new issue.

**Comment by jrandlestsla** [comment]
Yes, please do close it. Sorry I haven't been able to get around to working with this.

**Comment by mlhale7** [comment]
Thanks - no problem. Let us know if we can talk more about your workflow in the future so that we can share more records.
