### ISSUE TITLE
Rights Statements for TSLA

### ISSUE THREAD

**Issue by mlhale7** [DigitalLibraryofTennessee/DLTN_XSLT#49]
## Why are You Reporting an Issue

- [ ] Add New Set(s)
- [ ] Reingest Existing Set
- [ ] Report Problem with an Existing Set or XSL transform
- [X] Discuss Issue or Ask Question
- [ ] Other

## Discuss Issue or Ask Question

@jrandlestsla - In going through your metadata, I noticed that generally you assign the same rights statement: "While TSLA [or Library & Archives] houses an item, it does not necessarily hold the copyright on the item, nor may it be able to determine if the item is still protected under current copyright law. Users are solely responsible for determining the existence of such instances and for obtaining any other permissions and paying associated fees, that may be necessary for the intended use." This statement pretty closely aligns with the standardized rights statement ["Copyright Not Evaluated"](http://rightsstatements.org/vocab/CNE/1.0/). How would you feel about UT implementing this standardized rights statement for your collections? 

Also, we did an analysis of your collection to identify sets with missing rights statements. Can you share very briefly with me your workflow for assigning rights? I just wanted to see if identifying the records without rights statements might give us any additional insights on the state of those records. For instance, do you include rights statements when you create initial records for items that will be digitized in the future?

Thanks ahead of time for your input.

**Comment by jrandlestsla** [comment]
Yes, Jami and I have discussed changing over to copyright not evaluated as it does fit most of our statements. However, we wanted to change that in TeVA itself, since some of our collections are in the public domain, such as Founding Documents. I would prefer to do that in TeVA so those collections wouldn't need to be re-harvested. But I don't have the time to update that field this week.

Since I started here last year, we do assign rights when we initially upload all items. I also went back earlier this year to assign rights to everything in TeVA. Can you send me the list of items without rights statements? There honestly shouldn't be anything that's missing a statement. Something may have just fallen through the cracks.

**Comment by mlhale7** [comment]
I apologize for the delay in responding. I'm glad to hear that you and Jami are working on incorporating standardized rights statements. Please do that as you have time and we'll be able to re-ingest the sets once this has been implemented.

After looking into your sets we identified as having records with missing rights statements (bernhardt, p15138coll26, p15138coll2, p15138coll23, p15138coll33, and p15138coll38) a bit more, I discovered that the major issue is that you haven't mapped all of your fields in ContentDM. When we run QA on these sets our tool identifies all of them as missing rights because these values aren't present in the OAI-PMH you're sharing. For our purposes, they are missing from the metadata even though they're in your system. For instance, [http://cdm15138.contentdm.oclc.org/cdm/ref/collection/p15138coll26/id/1968](http://cdm15138.contentdm.oclc.org/cdm/ref/collection/p15138coll26/id/1968) is one record we identified as lacking rights, but I can see when I check your ContentDM display that you do have a field called "Digital Rights." While we don't subscribe to the idea of a digital copyright, mapping "Digital Rights" will make it so that we can share rights information for these items. Mark mentioned that @carolynfrunyon has quite a bit of experience with this and might be able to give you some pointers if needed.  You could also change the records that use this digital copyright idea to your more standard rights statement. I'm sharing the output from analysis of p15138coll26 for missing rights (493 total records) 
(https://github.com/DigitalLibraryofTennessee/DLTN_XSLT/files/1556235/missingrights_26.txt)
in case it might be helpful. 

Still, the mapping issue does not cover all of the sets that are missing rights. For instance, p15138coll33 has 5 records with missing rights and spot checking them quickly, it does not appear that there is a field within the records that could be mapped to rights. Here's one example record - [http://cdm15138.contentdm.oclc.org/cdm/ref/collection/p15138coll33/id/505](http://cdm15138.contentdm.oclc.org/cdm/ref/collection/p15138coll33/id/505). After you go through and do the mapping that is necessary, we can go back through and reassess which of your sets truly do not have rights. As it is I would have to go through and follow links to your records individually to determine this.

Let me know if you have questions.Thanks for your help with this.

[missingrights_26.txt]

**Comment by jrandlestsla** [comment]
Thanks for the spreadsheet. I understand the mapping issue and can fix it on my end. Some of those are collections that pre-date my being here, and I had assumed they were correctly mapped. I can easily fix those in coll33 as well and let you know when I'm done, then we can re-assess. This may take a few days, but I will let you know when I'm done.

**Comment by mlhale7** [comment]
Thanks Jennifer - I completely understand needing to deal with issues that pre-date one's employment. We can plan on correcting everything before the March ingest, so there's no hurry. I'm not sure what TSLA's stance is on digital copyright, but this could be an opportunity to re-evaluate this.

**Comment by jrandlestsla** [comment]
Thanks, Meredith! I appreciate the understanding.


I am looking at coll26 and there is a field mapped to Rights called Copyrights that has our usual statement. I see that some of those Copyrights fields are not filled in for some of the earlier records in that collection. (I thought I did a global replace for that field, but some of them didn't take.) I am going to fix that one right now. The digital rights field is not something we use anymore, so I am just getting rid of that field for that collection.


________________________________

**Comment by mlhale7** [comment]
Thanks for this. Unfortunately if some records in a set don't have rights (or any of the other DPLA required fields) we don't take any records from that set. Once those are updated we'll be able to take the whole set next time around. I'm glad to hear that the digital rights field is a thing of the past - just make sure some sort of statement is present in every record after this is removed.

**Comment by jrandlestsla** [comment]
They are all updated in that set. I am working on the others and will let you know when they're updated.

**Comment by jrandlestsla** [comment]
I think we've fixed every collection and are now using rightsstatements.org rights on every item.

**Comment by carolynfrunyon** [comment]
Awesome work, Jennifer!

**Comment by jrandlestsla** [comment]
Thank you! We're pretty excited. We are cleaning things up further for the future, so we'll have lots of improvements in the coming months.

**Comment by carolynfrunyon** [comment]
Metadata clean up is kinda fun, actually! It's so gratifying!

**Comment by jrandlestsla** [comment]
Yes it is! I love seeing things work when they didn't before.
