### ISSUE TITLE
Adding New UTC Sets p16877coll24

### ISSUE THREAD

**Issue by nhlasley** [DigitalLibraryofTennessee/DLTN_XSLT#55]
## Why are You Reporting an Issue

- [X] Add New Set(s)
- [ ] Reingest Existing Set
- [ ] Report Problem with an Existing Set or XSL transform
- [ ] Discuss Issue or Ask Question
- [ ] Other

## New Set(s) / Reharvest Existing Set

Only required if you're requesting sets to be added or reharvested.

* p16877coll24

@carolynfrunyon

**Comment by markpbaggett** [comment]
@nhlasley, thanks!  We;ll take a look at this for the February ingest.

**Comment by markpbaggett** [comment]
@nhlasley, this is done.  The set has been added and has passed QA.  If you're curious about what the final MODS looks like, here is a report of xpath occurrences:

`| key                                                                   | types                    | occurrences | percents            |
| --------------------------------------------------------------------- | ------------------------ | ----------- | ------------------- |
| _id                                                                   | ObjectId                 |         194 | 100.000000000000000 |
| metadata                                                              | Object                   |         194 | 100.000000000000000 |
| metadata.mods                                                         | Object                   |         194 | 100.000000000000000 |
| metadata.mods.@version                                                | String                   |         194 | 100.000000000000000 |
| metadata.mods.@xmlns                                                  | String                   |         194 | 100.000000000000000 |
| metadata.mods.@xmlns:xlink                                            | String                   |         194 | 100.000000000000000 |
| metadata.mods.@xmlns:xsi                                              | String                   |         194 | 100.000000000000000 |
| metadata.mods.@xsi:schemaLocation                                     | String                   |         194 | 100.000000000000000 |
| metadata.mods.abstract                                                | String                   |         194 | 100.000000000000000 |
| metadata.mods.accessCondition                                         | Object                   |         194 | 100.000000000000000 |
| metadata.mods.accessCondition.@type                                   | String                   |         194 | 100.000000000000000 |
| metadata.mods.accessCondition.@xlink:href                             | String                   |         194 | 100.000000000000000 |
| metadata.mods.identifier                                              | Object                   |         194 | 100.000000000000000 |
| metadata.mods.identifier.#text                                        | String                   |         194 | 100.000000000000000 |
| metadata.mods.identifier.@type                                        | String                   |         194 | 100.000000000000000 |
| metadata.mods.location                                                | Object                   |         194 | 100.000000000000000 |
| metadata.mods.location.url                                            | Array                    |         194 | 100.000000000000000 |
| metadata.mods.location.url.XX.#text                                   | String                   |         194 | 100.000000000000000 |
| metadata.mods.location.url.XX.@access                                 | String                   |         194 | 100.000000000000000 |
| metadata.mods.location.url.XX.@usage                                  | String                   |         194 | 100.000000000000000 |
| metadata.mods.name                                                    | Array (189),Object (5)   |         194 | 100.000000000000000 |
| metadata.mods.originInfo                                              | Object                   |         194 | 100.000000000000000 |
| metadata.mods.originInfo.dateCreated                                  | Object                   |         194 | 100.000000000000000 |
| metadata.mods.originInfo.dateCreated.#text                            | String                   |         194 | 100.000000000000000 |
| metadata.mods.originInfo.dateCreated.@encoding                        | String                   |         194 | 100.000000000000000 |
| metadata.mods.originInfo.dateCreated.@point                           | String                   |         194 | 100.000000000000000 |
| metadata.mods.originInfo.publisher                                    | Array                    |         194 | 100.000000000000000 |
| metadata.mods.physicalDescription                                     | Object                   |         194 | 100.000000000000000 |
| metadata.mods.physicalDescription.extent                              | String                   |         194 | 100.000000000000000 |
| metadata.mods.physicalDescription.form                                | String                   |         194 | 100.000000000000000 |
| metadata.mods.physicalDescription.internetMediaType                   | Array                    |         194 | 100.000000000000000 |
| metadata.mods.recordInfo                                              | Object                   |         194 | 100.000000000000000 |
| metadata.mods.recordInfo.languageOfCataloging                         | Object                   |         194 | 100.000000000000000 |
| metadata.mods.recordInfo.languageOfCataloging.languageTerm            | Object                   |         194 | 100.000000000000000 |
| metadata.mods.recordInfo.languageOfCataloging.languageTerm.#text      | String                   |         194 | 100.000000000000000 |
| metadata.mods.recordInfo.languageOfCataloging.languageTerm.@authority | String                   |         194 | 100.000000000000000 |
| metadata.mods.recordInfo.languageOfCataloging.languageTerm.@term      | String                   |         194 | 100.000000000000000 |
| metadata.mods.recordInfo.recordChangeDate                             | String                   |         194 | 100.000000000000000 |
| metadata.mods.recordInfo.recordContentSource                          | String                   |         194 | 100.000000000000000 |
| metadata.mods.recordInfo.recordOrigin                                 | String                   |         194 | 100.000000000000000 |
| metadata.mods.relatedItem                                             | Array                    |         194 | 100.000000000000000 |
| metadata.mods.relatedItem.XX.@displayLabel                            | String                   |         194 | 100.000000000000000 |
| metadata.mods.relatedItem.XX.@type                                    | String                   |         194 | 100.000000000000000 |
| metadata.mods.relatedItem.XX.titleInfo                                | Object                   |         194 | 100.000000000000000 |
| metadata.mods.relatedItem.XX.titleInfo.title                          | Array (194),String (194) |         194 | 100.000000000000000 |
| metadata.mods.subject                                                 | Array                    |         194 | 100.000000000000000 |
| metadata.mods.subject.XX.geographic                                   | String                   |         194 | 100.000000000000000 |
| metadata.mods.subject.XX.topic                                        | String                   |         194 | 100.000000000000000 |
| metadata.mods.titleInfo                                               | Object                   |         194 | 100.000000000000000 |
| metadata.mods.titleInfo.title                                         | String                   |         194 | 100.000000000000000 |
| metadata.mods.typeOfResource                                          | String                   |         194 | 100.000000000000000 |
| oai_provider                                                          | String                   |         194 | 100.000000000000000 |
| record_id                                                             | String                   |         194 | 100.000000000000000 |
| set                                                                   | String                   |         194 | 100.000000000000000 |
| metadata.mods.name.XX.namePart                                        | String                   |         189 |  97.422680412371136 |
| metadata.mods.name.XX.role                                            | Object                   |         189 |  97.422680412371136 |
| metadata.mods.name.XX.role.roleTerm                                   | Object                   |         189 |  97.422680412371136 |
| metadata.mods.name.XX.role.roleTerm.#text                             | String                   |         189 |  97.422680412371136 |
| metadata.mods.name.XX.role.roleTerm.@authority                        | String                   |         189 |  97.422680412371136 |
| metadata.mods.name.XX.role.roleTerm.@authorityURI                     | String                   |         189 |  97.422680412371136 |
| metadata.mods.name.namePart                                           | String                   |           5 |   2.577319587628866 |
| metadata.mods.name.role                                               | Object                   |           5 |   2.577319587628866 |
| metadata.mods.name.role.roleTerm                                      | Object                   |           5 |   2.577319587628866 |
| metadata.mods.name.role.roleTerm.#text                                | String                   |           5 |   2.577319587628866 |
| metadata.mods.name.role.roleTerm.@authority                           | String                   |           5 |   2.577319587628866 |
| metadata.mods.name.role.roleTerm.@authorityURI                        | String                   |           5 |   2.577319587628866 |
+--------------------------------------------------------------------------------------------------------------------------------------+
`
