### ISSUE TITLE
Re-harvest UTC Sets p16877coll21, p16877coll2, and p16877coll6

### ISSUE THREAD

**Issue by carolynfrunyon** [DigitalLibraryofTennessee/DLTN_XSLT#56]
## Why are You Reporting an Issue

- [ ] Add New Set(s)
- [x] Reingest Existing Set
- [ ] Report Problem with an Existing Set or XSL transform
- [ ] Discuss Issue or Ask Question
- [ ] Other

## New Set(s) / Reharvest Existing Set

* p16877coll21
* p16877coll2
* p16877coll6
p16877coll24

I added some more items and improved the metadata in two of these sets. Would you mind re-harvesting so that we're giving DPLA our most up-to-date information?

Thank you for your help! It is much appreciated!

All the best,
Carolyn

**Comment by markpbaggett** [comment]
@carolynfrunyon, working on this now.

**Comment by markpbaggett** [comment]
This is done.  Here is a report verifying that all required elements are there for all 4 collections:

| key                                                                   | types                    | occurrences | percents            |
| --------------------------------------------------------------------- | ------------------------ | ----------- | ------------------- |
| _id                                                                   | ObjectId                 |         530 | 100.000000000000000 |
| metadata                                                              | Object                   |         530 | 100.000000000000000 |
| metadata.mods                                                         | Object                   |         530 | 100.000000000000000 |
| metadata.mods.@version                                                | String                   |         530 | 100.000000000000000 |
| metadata.mods.@xmlns                                                  | String                   |         530 | 100.000000000000000 |
| metadata.mods.@xmlns:xlink                                            | String                   |         530 | 100.000000000000000 |
| metadata.mods.@xmlns:xsi                                              | String                   |         530 | 100.000000000000000 |
| metadata.mods.@xsi:schemaLocation                                     | String                   |         530 | 100.000000000000000 |
| metadata.mods.abstract                                                | String (443),Array (87)  |         530 | 100.000000000000000 |
| metadata.mods.accessCondition                                         | Object                   |         530 | 100.000000000000000 |
| metadata.mods.accessCondition.@type                                   | String                   |         530 | 100.000000000000000 |
| metadata.mods.accessCondition.@xlink:href                             | String                   |         530 | 100.000000000000000 |
| metadata.mods.identifier                                              | Array (167),Object (363) |         530 | 100.000000000000000 |
| metadata.mods.location                                                | Object                   |         530 | 100.000000000000000 |
| metadata.mods.location.url                                            | Array                    |         530 | 100.000000000000000 |
| metadata.mods.location.url.XX.#text                                   | String                   |         530 | 100.000000000000000 |
| metadata.mods.location.url.XX.@access                                 | String                   |         530 | 100.000000000000000 |
| metadata.mods.location.url.XX.@usage                                  | String                   |         530 | 100.000000000000000 |
| metadata.mods.name                                                    | Array (455),Object (75)  |         530 | 100.000000000000000 |
| metadata.mods.originInfo                                              | Object                   |         530 | 100.000000000000000 |
| metadata.mods.originInfo.publisher                                    | String (330),Array (200) |         530 | 100.000000000000000 |
| metadata.mods.physicalDescription                                     | Object                   |         530 | 100.000000000000000 |
| metadata.mods.physicalDescription.form                                | String (504),Array (26)  |         530 | 100.000000000000000 |
| metadata.mods.physicalDescription.internetMediaType                   | String (230),Array (300) |         530 | 100.000000000000000 |
| metadata.mods.recordInfo                                              | Object                   |         530 | 100.000000000000000 |
| metadata.mods.recordInfo.languageOfCataloging                         | Object                   |         530 | 100.000000000000000 |
| metadata.mods.recordInfo.languageOfCataloging.languageTerm            | Object                   |         530 | 100.000000000000000 |
| metadata.mods.recordInfo.languageOfCataloging.languageTerm.#text      | String                   |         530 | 100.000000000000000 |
| metadata.mods.recordInfo.languageOfCataloging.languageTerm.@authority | String                   |         530 | 100.000000000000000 |
| metadata.mods.recordInfo.languageOfCataloging.languageTerm.@term      | String                   |         530 | 100.000000000000000 |
| metadata.mods.recordInfo.recordChangeDate                             | String                   |         530 | 100.000000000000000 |
| metadata.mods.recordInfo.recordContentSource                          | String                   |         530 | 100.000000000000000 |
| metadata.mods.recordInfo.recordOrigin                                 | String                   |         530 | 100.000000000000000 |
| metadata.mods.relatedItem                                             | Array                    |         530 | 100.000000000000000 |
| metadata.mods.relatedItem.XX.@displayLabel                            | String                   |         530 | 100.000000000000000 |
| metadata.mods.relatedItem.XX.@type                                    | String                   |         530 | 100.000000000000000 |
| metadata.mods.relatedItem.XX.titleInfo                                | Object                   |         530 | 100.000000000000000 |
| metadata.mods.relatedItem.XX.titleInfo.title                          | Array (530),String (530) |         530 | 100.000000000000000 |
| metadata.mods.subject                                                 | Array                    |         530 | 100.000000000000000 |
| metadata.mods.subject.XX.topic                                        | String (530),null (12)   |         530 | 100.000000000000000 |
| metadata.mods.titleInfo                                               | Object                   |         530 | 100.000000000000000 |
| metadata.mods.titleInfo.title                                         | String                   |         530 | 100.000000000000000 |
| metadata.mods.typeOfResource                                          | String                   |         530 | 100.000000000000000 |
| oai_provider                                                          | String                   |         530 | 100.000000000000000 |
| record_id                                                             | String                   |         530 | 100.000000000000000 |
| metadata.mods.originInfo.dateCreated                                  | Object (466),Array (63)  |         529 |  99.811320754716988 |
| metadata.mods.subject.XX.geographic                                   | String                   |         529 |  99.811320754716988 |
| metadata.mods.physicalDescription.extent                              | String                   |         526 |  99.245283018867923 |
| metadata.mods.originInfo.dateCreated.#text                            | String                   |         466 |  87.924528301886795 |
| metadata.mods.originInfo.dateCreated.@encoding                        | String                   |         466 |  87.924528301886795 |
| metadata.mods.originInfo.dateCreated.@point                           | String                   |         466 |  87.924528301886795 |
| metadata.mods.name.XX.namePart                                        | String                   |         455 |  85.849056603773590 |
| metadata.mods.name.XX.role                                            | Object                   |         455 |  85.849056603773590 |
| metadata.mods.name.XX.role.roleTerm                                   | Object                   |         455 |  85.849056603773590 |
| metadata.mods.name.XX.role.roleTerm.#text                             | String                   |         455 |  85.849056603773590 |
| metadata.mods.name.XX.role.roleTerm.@authority                        | String                   |         455 |  85.849056603773590 |
| metadata.mods.name.XX.role.roleTerm.@authorityURI                     | String                   |         455 |  85.849056603773590 |
| metadata.mods.identifier.#text                                        | String                   |         363 |  68.490566037735846 |
| metadata.mods.identifier.@type                                        | String                   |         363 |  68.490566037735846 |
| set                                                                   | String                   |         194 |  36.603773584905660 |
| metadata.mods.identifier.XX.#text                                     | String                   |         167 |  31.509433962264151 |
| metadata.mods.identifier.XX.@type                                     | String                   |         167 |  31.509433962264151 |
| metadata.mods.name.namePart                                           | String                   |          75 |  14.150943396226415 |
| metadata.mods.name.role                                               | Object                   |          75 |  14.150943396226415 |
| metadata.mods.name.role.roleTerm                                      | Object                   |          75 |  14.150943396226415 |
| metadata.mods.name.role.roleTerm.#text                                | String                   |          75 |  14.150943396226415 |
| metadata.mods.name.role.roleTerm.@authority                           | String                   |          75 |  14.150943396226415 |
| metadata.mods.name.role.roleTerm.@authorityURI                        | String                   |          75 |  14.150943396226415 |
| metadata.mods.originInfo.dateCreated.XX.#text                         | String                   |          63 |  11.886792452830189 |
| metadata.mods.originInfo.dateCreated.XX.@encoding                     | String                   |          63 |  11.886792452830189 |
| metadata.mods.originInfo.dateCreated.XX.@point                        | String                   |          63 |  11.886792452830189 |

**Comment by carolynfrunyon** [comment]
Thanks was fast! Thanks @markpbaggett!
