### ISSUE TITLE
Change rights to accessCondition rule for Country Music Hall of Fame

### ISSUE THREAD

**Issue by markpbaggett** [DigitalLibraryofTennessee/DLTN_XSLT#57]
## Why are You Reporting an Issue

- [ ] Add New Set(s)
- [ ] Reingest Existing Set
- [ ] Report Problem with an Existing Set or XSL transform
- [x] Discuss Issue or Ask Question
- [ ] Other

## Question

We've been asked to reharvest CMHF as OAI QDC. 13 of the 6717 objects are missing a rights statement.  The other 6704 objects have the exact same rights statement:

>This audio file is the property of the Country Music Hall of Fame® and Museum and may be protected by U.S. and international copyright laws. The file may not be downloaded, reproduced, or distributed without permission. End users must obtain all required permissions or consents from the owners of such rights. To inquire about use permissions and obtain a high-quality version of this, contact audio@countrymusichalloffame.org. Please cite audio file information in email.

Instead of asking Lee to fix this, what if we were to write a standard rights statement using rightsstatements.org.  Then, take Lee's text and add it to another node:

https://github.com/dpla/ingestion/blob/3ee06770c4a6d6e663f0d207a429b0b33b40f641/lib/mappers/tn_mapper.py#L71

This is the sort of thing that has been suggested from DPLA in the past as far as keeping "local notes" about use and reproduction.

Let me know what you all think. Regardless if the 13 rights statements are "fixed" by the provider, we still have to figure out how to get these to standardized rights at some point.

**Comment by carolynfrunyon** [comment]
I think we should ask our partners to fix the underlying issue. At the very lead, CMHF could add their local rights statement to the 13 objects that lack one. We should also communicate a need to apply a standardized rights statement per our guidelines from DPLA. Would you like to me liaise the CMHF or is that something you want to handle on your end?

**Comment by markpbaggett** [comment]
@carolynfrunyon that would be great if you would be willing to do that.  It almost seems to me that what they want to say is either:

1. In Copyright or Copyright Undetermined
2. End users must obtain all required permissions or consents from the owners of such rights.  To inquire about use permissions and obtain a high-quality version of this, contact audio@coutrymusichalloffame.org.  Please cite audio file information in email.

If this is true, and this applies to all of their stuff, I still think it's easier for UTK to serialize this to the appropriate fields rather than trying to parse the XML and then QAing anytime we repull to make sure something isn't missing. Therefore, I'm fine with us serializing if they'd prefer us to do that.

Since Monday is the big day for our harvest, I'll hold off on adding the new objects until next time.

**Comment by carolynfrunyon** [comment]
@markpbaggett and @mlhale7, I've contacted Lee Boulie and the CMHF regarding standardized rights statements. Would either of you like me to start copying you on these emails?

**Comment by mlhale7** [comment]
@carolynfrunyon thanks so much for helping us out with this. I would like to be copied on the emails - thank you for asking.

**Comment by carolynfrunyon** [comment]
@markpbaggett and @mlhale7 , I spoke with Lee Boulie at the Country Music of of Fame and Museum. They are going to incorporate URIs from rightsstatements.org or Creative Commons. They'll need to vet some of this through their legal counsel, so it may take some time. Until then, we can hold off re-harvesting from them. Also, Lee mentioned that she would be interested in serving on the DLTN committee. @markpbaggett, I leave that in your capable hands.
