### ISSUE TITLE
New Sets from UTC: p16877coll26 and p16877coll27

### ISSUE THREAD

**Issue by carolynfrunyon** [DigitalLibraryofTennessee/DLTN_XSLT#67]
## Why are You Reporting an Issue
- [x] Add New Set(s)
- [ ] Reingest Existing Set
- [ ] Report Problem with an Existing Set or XSL transform
- [ ] Discuss Issue or Ask Question
- [ ] Other

## New Set(s) 
* p16877coll26
* p16877coll27

Descriptions for each new set is available from http://cdm16877.contentdm.oclc.org/oai/oai.php?verb=ListSets.

**Comment by mlhale7** [comment]
@carolynfrunyon - these sets have been QA'd and ingested.

**Comment by carolynfrunyon** [comment]
Thanks @mlhale7!
