### ISSUE TITLE
Provider Specific Manifest Catalogs

### ISSUE THREAD

**Issue by markpbaggett** [DigitalLibraryofTennessee/DLTN_XSLT#82]
## Why are You Reporting an Issue

- [ ] Add New Set(s)
- [ ] Reingest Existing Set
- [x] Report Problem with an Existing Set or XSL transform
- [ ] Discuss Issue or Ask Question
- [ ] Other

Our IIIF work has created a mess for submitting, reviewing, approving, and merging pull requests.  Instead of doing things in one big file, I propose we do this in provider specific catalogs.

**Comment by CanOfBees** [comment]
@markpbaggett this is a great idea: granularity will make debugging and tracking changes much easier.

Thanks!
